/* tslint:disable */
/* eslint-disable */
/**
 * BoxLite Runner API
 * BoxLite Runner API
 *
 * The version of the OpenAPI document: v0.0.0-dev
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 *
 * @export
 * @interface ArtifactDigestResponse
 */
export interface ArtifactDigestResponse {
    /**
     *
     * @type {string}
     * @memberof ArtifactDigestResponse
     */
    'hash'?: string;
    /**
     *
     * @type {number}
     * @memberof ArtifactDigestResponse
     */
    'sizeGB'?: number;
}
