/* tslint:disable */
/* eslint-disable */
/**
 * BoxLite Runner API
 * BoxLite Runner API
 *
 * The version of the OpenAPI document: v0.0.0-dev
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

// May contain unused imports in some cases
// @ts-ignore
import type { RegistryDTO } from './registry-dto'

/**
 *
 * @export
 * @interface BuildArtifactRequestDTO
 */
export interface BuildArtifactRequestDTO {
  /**
   * Artifact ref or the build\'s hash
   * @type {string}
   * @memberof BuildArtifactRequestDTO
   */
  artifactRef?: string
  /**
   *
   * @type {Array<string>}
   * @memberof BuildArtifactRequestDTO
   */
  context?: Array<string>
  /**
   *
   * @type {string}
   * @memberof BuildArtifactRequestDTO
   */
  dockerfile: string
  /**
   *
   * @type {string}
   * @memberof BuildArtifactRequestDTO
   */
  organizationId: string
  /**
   *
   * @type {boolean}
   * @memberof BuildArtifactRequestDTO
   */
  pushToInternalRegistry?: boolean
  /**
   *
   * @type {RegistryDTO}
   * @memberof BuildArtifactRequestDTO
   */
  registry?: RegistryDTO
  /**
   *
   * @type {Array<RegistryDTO>}
   * @memberof BuildArtifactRequestDTO
   */
  sourceRegistries?: Array<RegistryDTO>
}
