/* tslint:disable */
/* eslint-disable */
/**
 * BoxLite Runner API
 * BoxLite Runner API
 *
 * The version of the OpenAPI document: v0.0.0-dev
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

// May contain unused imports in some cases
// @ts-ignore
import type { RegistryDTO } from './registry-dto'

/**
 *
 * @export
 * @interface InspectArtifactInRegistryRequest
 */
export interface InspectArtifactInRegistryRequest {
  /**
   *
   * @type {string}
   * @memberof InspectArtifactInRegistryRequest
   */
  artifactRef: string
  /**
   *
   * @type {RegistryDTO}
   * @memberof InspectArtifactInRegistryRequest
   */
  registry?: RegistryDTO
}
