/* tslint:disable */
/* eslint-disable */
/**
 * BoxLite Runner API
 * BoxLite Runner API
 *
 * The version of the OpenAPI document: v0.0.0-dev
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { RegistryDTO } from './registry-dto';

/**
 *
 * @export
 * @interface PullArtifactRequestDTO
 */
export interface PullArtifactRequestDTO {
    /**
     *
     * @type {string}
     * @memberof PullArtifactRequestDTO
     */
    'destinationRef'?: string;
    /**
     *
     * @type {RegistryDTO}
     * @memberof PullArtifactRequestDTO
     */
    'destinationRegistry'?: RegistryDTO;
    /**
     *
     * @type {string}
     * @memberof PullArtifactRequestDTO
     */
    'newTag'?: string;
    /**
     *
     * @type {RegistryDTO}
     * @memberof PullArtifactRequestDTO
     */
    'registry'?: RegistryDTO;
    /**
     *
     * @type {string}
     * @memberof PullArtifactRequestDTO
     */
    'artifactRef': string;
}
