/* tslint:disable */
/* eslint-disable */
/**
 * BoxLite Runner API
 * BoxLite Runner API
 *
 * The version of the OpenAPI document: v0.0.0-dev
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface TagImageRequestDTO
 */
export interface TagImageRequestDTO {
  /**
   *
   * @type {string}
   * @memberof TagImageRequestDTO
   */
  sourceImage: string
  /**
   *
   * @type {string}
   * @memberof TagImageRequestDTO
   */
  targetImage: string
}
