/*
 * Copyright 2025 Daytona Platforms Inc.
 * Modified by BoxLite AI, 2025-2026
 * SPDX-License-Identifier: AGPL-3.0
 */

export enum JobType {
  CREATE_SANDBOX = 'CREATE_SANDBOX',
  START_SANDBOX = 'START_SANDBOX',
  STOP_SANDBOX = 'STOP_SANDBOX',
  DESTROY_SANDBOX = 'DESTROY_SANDBOX',
  RESIZE_SANDBOX = 'RESIZE_SANDBOX',
  CREATE_BACKUP = 'CREATE_BACKUP',
  BUILD_ARTIFACT = 'BUILD_ARTIFACT',
  PULL_ARTIFACT = 'PULL_ARTIFACT',
  RECOVER_SANDBOX = 'RECOVER_SANDBOX',
  INSPECT_ARTIFACT_IN_REGISTRY = 'INSPECT_ARTIFACT_IN_REGISTRY',
  REMOVE_ARTIFACT = 'REMOVE_ARTIFACT',
  UPDATE_SANDBOX_NETWORK_SETTINGS = 'UPDATE_SANDBOX_NETWORK_SETTINGS',
}
