/* tslint:disable */
/* eslint-disable */
/**
 * BoxLite
 * BoxLite AI platform API Docs
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@boxlite.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from '../configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on savedImage conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, type RequestArgs, BaseAPI, RequiredError, operationServerMap } from '../base';
// @ts-ignore
import type { SavedImageDto } from '../models';
// @ts-ignore
import type { CreateSavedImage } from '../models';
// @ts-ignore
import type { PaginatedSavedImages } from '../models';
// @ts-ignore
import type { SetSavedImageGeneralStatus } from '../models';
// @ts-ignore
import type { Url } from '../models';
/**
 * SavedImagesApi - axios parameter creator
 * @export
 */
export const SavedImagesApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         *
         * @summary Activate a box savedImage
         * @param {string} id SavedImage ID
         * @param {string} [xBoxLiteOrganizationID] Use with JWT to specify the organization ID
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        activateSavedImage: async (id: string, xBoxLiteOrganizationID?: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('activateSavedImage', 'id', id)
            const localVarPath = `/saved-images/{id}/activate`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearer required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            // authentication oauth2 required



            if (xBoxLiteOrganizationID != null) {
                localVarHeaderParameter['X-BoxLite-Organization-ID'] = String(xBoxLiteOrganizationID);
            }
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         *
         * @summary Create a new box savedImage
         * @param {CreateSavedImage} createSavedImage
         * @param {string} [xBoxLiteOrganizationID] Use with JWT to specify the organization ID
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        createSavedImage: async (createSavedImage: CreateSavedImage, xBoxLiteOrganizationID?: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'createSavedImage' is not null or undefined
            assertParamExists('createSavedImage', 'createSavedImage', createSavedImage)
            const localVarPath = `/saved-images`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearer required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            // authentication oauth2 required



            localVarHeaderParameter['Content-Type'] = 'application/json';

            if (xBoxLiteOrganizationID != null) {
                localVarHeaderParameter['X-BoxLite-Organization-ID'] = String(xBoxLiteOrganizationID);
            }
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(createSavedImage, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         *
         * @summary Deactivate a box savedImage
         * @param {string} id SavedImage ID
         * @param {string} [xBoxLiteOrganizationID] Use with JWT to specify the organization ID
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        deactivateSavedImage: async (id: string, xBoxLiteOrganizationID?: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('deactivateSavedImage', 'id', id)
            const localVarPath = `/saved-images/{id}/deactivate`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearer required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            // authentication oauth2 required



            if (xBoxLiteOrganizationID != null) {
                localVarHeaderParameter['X-BoxLite-Organization-ID'] = String(xBoxLiteOrganizationID);
            }
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         *
         * @summary Get box savedImage by ID or name
         * @param {string} id SavedImage ID or name
         * @param {string} [xBoxLiteOrganizationID] Use with JWT to specify the organization ID
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getSavedImage: async (id: string, xBoxLiteOrganizationID?: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('getSavedImage', 'id', id)
            const localVarPath = `/saved-images/{id}`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearer required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            // authentication oauth2 required



            if (xBoxLiteOrganizationID != null) {
                localVarHeaderParameter['X-BoxLite-Organization-ID'] = String(xBoxLiteOrganizationID);
            }
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * This endpoint is deprecated. Use `getSavedImageBuildLogsUrl` instead.
         * @summary Get box savedImage build logs
         * @param {string} id SavedImage ID
         * @param {string} [xBoxLiteOrganizationID] Use with JWT to specify the organization ID
         * @param {boolean} [follow] Whether to follow the logs stream
         * @param {*} [options] Override http request option.
         * @deprecated
         * @throws {RequiredError}
         */
        getSavedImageBuildLogs: async (id: string, xBoxLiteOrganizationID?: string, follow?: boolean, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('getSavedImageBuildLogs', 'id', id)
            const localVarPath = `/saved-images/{id}/build-logs`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearer required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            // authentication oauth2 required

            if (follow !== undefined) {
                localVarQueryParameter['follow'] = follow;
            }



            if (xBoxLiteOrganizationID != null) {
                localVarHeaderParameter['X-BoxLite-Organization-ID'] = String(xBoxLiteOrganizationID);
            }
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         *
         * @summary Get box savedImage build logs URL
         * @param {string} id SavedImage ID
         * @param {string} [xBoxLiteOrganizationID] Use with JWT to specify the organization ID
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getSavedImageBuildLogsUrl: async (id: string, xBoxLiteOrganizationID?: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('getSavedImageBuildLogsUrl', 'id', id)
            const localVarPath = `/saved-images/{id}/build-logs-url`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearer required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            // authentication oauth2 required



            if (xBoxLiteOrganizationID != null) {
                localVarHeaderParameter['X-BoxLite-Organization-ID'] = String(xBoxLiteOrganizationID);
            }
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         *
         * @summary List box savedImages
         * @param {string} [xBoxLiteOrganizationID] Use with JWT to specify the organization ID
         * @param {number} [page] Page number of the results
         * @param {number} [limit] Number of results per page
         * @param {string} [name] Filter by partial name match
         * @param {ListSavedImagesSortEnum} [sort] Field to sort by
         * @param {ListSavedImagesOrderEnum} [order] Direction to sort by
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        listSavedImages: async (xBoxLiteOrganizationID?: string, page?: number, limit?: number, name?: string, sort?: ListSavedImagesSortEnum, order?: ListSavedImagesOrderEnum, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/saved-images`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearer required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            // authentication oauth2 required

            if (page !== undefined) {
                localVarQueryParameter['page'] = page;
            }

            if (limit !== undefined) {
                localVarQueryParameter['limit'] = limit;
            }

            if (name !== undefined) {
                localVarQueryParameter['name'] = name;
            }

            if (sort !== undefined) {
                localVarQueryParameter['sort'] = sort;
            }

            if (order !== undefined) {
                localVarQueryParameter['order'] = order;
            }



            if (xBoxLiteOrganizationID != null) {
                localVarHeaderParameter['X-BoxLite-Organization-ID'] = String(xBoxLiteOrganizationID);
            }
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         *
         * @summary Delete box savedImage
         * @param {string} id SavedImage ID
         * @param {string} [xBoxLiteOrganizationID] Use with JWT to specify the organization ID
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        removeSavedImage: async (id: string, xBoxLiteOrganizationID?: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('removeSavedImage', 'id', id)
            const localVarPath = `/saved-images/{id}`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'DELETE', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearer required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            // authentication oauth2 required



            if (xBoxLiteOrganizationID != null) {
                localVarHeaderParameter['X-BoxLite-Organization-ID'] = String(xBoxLiteOrganizationID);
            }
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         *
         * @summary Set box savedImage general status
         * @param {string} id SavedImage ID
         * @param {SetSavedImageGeneralStatus} setSavedImageGeneralStatus
         * @param {string} [xBoxLiteOrganizationID] Use with JWT to specify the organization ID
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        setSavedImageGeneralStatus: async (id: string, setSavedImageGeneralStatus: SetSavedImageGeneralStatus, xBoxLiteOrganizationID?: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('setSavedImageGeneralStatus', 'id', id)
            // verify required parameter 'setSavedImageGeneralStatus' is not null or undefined
            assertParamExists('setSavedImageGeneralStatus', 'setSavedImageGeneralStatus', setSavedImageGeneralStatus)
            const localVarPath = `/saved-images/{id}/general`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'PATCH', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearer required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            // authentication oauth2 required



            localVarHeaderParameter['Content-Type'] = 'application/json';

            if (xBoxLiteOrganizationID != null) {
                localVarHeaderParameter['X-BoxLite-Organization-ID'] = String(xBoxLiteOrganizationID);
            }
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(setSavedImageGeneralStatus, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * SavedImagesApi - functional programming interface
 * @export
 */
export const SavedImagesApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = SavedImagesApiAxiosParamCreator(configuration)
    return {
        /**
         *
         * @summary Activate a box savedImage
         * @param {string} id SavedImage ID
         * @param {string} [xBoxLiteOrganizationID] Use with JWT to specify the organization ID
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async activateSavedImage(id: string, xBoxLiteOrganizationID?: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<SavedImageDto>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.activateSavedImage(id, xBoxLiteOrganizationID, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['SavedImagesApi.activateSavedImage']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         *
         * @summary Create a new box savedImage
         * @param {CreateSavedImage} createSavedImage
         * @param {string} [xBoxLiteOrganizationID] Use with JWT to specify the organization ID
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async createSavedImage(createSavedImage: CreateSavedImage, xBoxLiteOrganizationID?: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<SavedImageDto>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.createSavedImage(createSavedImage, xBoxLiteOrganizationID, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['SavedImagesApi.createSavedImage']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         *
         * @summary Deactivate a box savedImage
         * @param {string} id SavedImage ID
         * @param {string} [xBoxLiteOrganizationID] Use with JWT to specify the organization ID
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async deactivateSavedImage(id: string, xBoxLiteOrganizationID?: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.deactivateSavedImage(id, xBoxLiteOrganizationID, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['SavedImagesApi.deactivateSavedImage']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         *
         * @summary Get box savedImage by ID or name
         * @param {string} id SavedImage ID or name
         * @param {string} [xBoxLiteOrganizationID] Use with JWT to specify the organization ID
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getSavedImage(id: string, xBoxLiteOrganizationID?: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<SavedImageDto>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getSavedImage(id, xBoxLiteOrganizationID, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['SavedImagesApi.getSavedImage']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * This endpoint is deprecated. Use `getSavedImageBuildLogsUrl` instead.
         * @summary Get box savedImage build logs
         * @param {string} id SavedImage ID
         * @param {string} [xBoxLiteOrganizationID] Use with JWT to specify the organization ID
         * @param {boolean} [follow] Whether to follow the logs stream
         * @param {*} [options] Override http request option.
         * @deprecated
         * @throws {RequiredError}
         */
        async getSavedImageBuildLogs(id: string, xBoxLiteOrganizationID?: string, follow?: boolean, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getSavedImageBuildLogs(id, xBoxLiteOrganizationID, follow, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['SavedImagesApi.getSavedImageBuildLogs']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         *
         * @summary Get box savedImage build logs URL
         * @param {string} id SavedImage ID
         * @param {string} [xBoxLiteOrganizationID] Use with JWT to specify the organization ID
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getSavedImageBuildLogsUrl(id: string, xBoxLiteOrganizationID?: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Url>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getSavedImageBuildLogsUrl(id, xBoxLiteOrganizationID, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['SavedImagesApi.getSavedImageBuildLogsUrl']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         *
         * @summary List box savedImages
         * @param {string} [xBoxLiteOrganizationID] Use with JWT to specify the organization ID
         * @param {number} [page] Page number of the results
         * @param {number} [limit] Number of results per page
         * @param {string} [name] Filter by partial name match
         * @param {ListSavedImagesSortEnum} [sort] Field to sort by
         * @param {ListSavedImagesOrderEnum} [order] Direction to sort by
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async listSavedImages(xBoxLiteOrganizationID?: string, page?: number, limit?: number, name?: string, sort?: ListSavedImagesSortEnum, order?: ListSavedImagesOrderEnum, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Array<SavedImageDto> | PaginatedSavedImages>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.listSavedImages(xBoxLiteOrganizationID, page, limit, name, sort, order, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['SavedImagesApi.listSavedImages']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         *
         * @summary Delete box savedImage
         * @param {string} id SavedImage ID
         * @param {string} [xBoxLiteOrganizationID] Use with JWT to specify the organization ID
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async removeSavedImage(id: string, xBoxLiteOrganizationID?: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.removeSavedImage(id, xBoxLiteOrganizationID, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['SavedImagesApi.removeSavedImage']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         *
         * @summary Set box savedImage general status
         * @param {string} id SavedImage ID
         * @param {SetSavedImageGeneralStatus} setSavedImageGeneralStatus
         * @param {string} [xBoxLiteOrganizationID] Use with JWT to specify the organization ID
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async setSavedImageGeneralStatus(id: string, setSavedImageGeneralStatus: SetSavedImageGeneralStatus, xBoxLiteOrganizationID?: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<SavedImageDto>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.setSavedImageGeneralStatus(id, setSavedImageGeneralStatus, xBoxLiteOrganizationID, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['SavedImagesApi.setSavedImageGeneralStatus']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * SavedImagesApi - factory interface
 * @export
 */
export const SavedImagesApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = SavedImagesApiFp(configuration)
    return {
        /**
         *
         * @summary Activate a box savedImage
         * @param {string} id SavedImage ID
         * @param {string} [xBoxLiteOrganizationID] Use with JWT to specify the organization ID
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        activateSavedImage(id: string, xBoxLiteOrganizationID?: string, options?: RawAxiosRequestConfig): AxiosPromise<SavedImageDto> {
            return localVarFp.activateSavedImage(id, xBoxLiteOrganizationID, options).then((request) => request(axios, basePath));
        },
        /**
         *
         * @summary Create a new box savedImage
         * @param {CreateSavedImage} createSavedImage
         * @param {string} [xBoxLiteOrganizationID] Use with JWT to specify the organization ID
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        createSavedImage(createSavedImage: CreateSavedImage, xBoxLiteOrganizationID?: string, options?: RawAxiosRequestConfig): AxiosPromise<SavedImageDto> {
            return localVarFp.createSavedImage(createSavedImage, xBoxLiteOrganizationID, options).then((request) => request(axios, basePath));
        },
        /**
         *
         * @summary Deactivate a box savedImage
         * @param {string} id SavedImage ID
         * @param {string} [xBoxLiteOrganizationID] Use with JWT to specify the organization ID
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        deactivateSavedImage(id: string, xBoxLiteOrganizationID?: string, options?: RawAxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.deactivateSavedImage(id, xBoxLiteOrganizationID, options).then((request) => request(axios, basePath));
        },
        /**
         *
         * @summary Get box savedImage by ID or name
         * @param {string} id SavedImage ID or name
         * @param {string} [xBoxLiteOrganizationID] Use with JWT to specify the organization ID
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getSavedImage(id: string, xBoxLiteOrganizationID?: string, options?: RawAxiosRequestConfig): AxiosPromise<SavedImageDto> {
            return localVarFp.getSavedImage(id, xBoxLiteOrganizationID, options).then((request) => request(axios, basePath));
        },
        /**
         * This endpoint is deprecated. Use `getSavedImageBuildLogsUrl` instead.
         * @summary Get box savedImage build logs
         * @param {string} id SavedImage ID
         * @param {string} [xBoxLiteOrganizationID] Use with JWT to specify the organization ID
         * @param {boolean} [follow] Whether to follow the logs stream
         * @param {*} [options] Override http request option.
         * @deprecated
         * @throws {RequiredError}
         */
        getSavedImageBuildLogs(id: string, xBoxLiteOrganizationID?: string, follow?: boolean, options?: RawAxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.getSavedImageBuildLogs(id, xBoxLiteOrganizationID, follow, options).then((request) => request(axios, basePath));
        },
        /**
         *
         * @summary Get box savedImage build logs URL
         * @param {string} id SavedImage ID
         * @param {string} [xBoxLiteOrganizationID] Use with JWT to specify the organization ID
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getSavedImageBuildLogsUrl(id: string, xBoxLiteOrganizationID?: string, options?: RawAxiosRequestConfig): AxiosPromise<Url> {
            return localVarFp.getSavedImageBuildLogsUrl(id, xBoxLiteOrganizationID, options).then((request) => request(axios, basePath));
        },
        /**
         *
         * @summary List box savedImages
         * @param {string} [xBoxLiteOrganizationID] Use with JWT to specify the organization ID
         * @param {number} [page] Page number of the results
         * @param {number} [limit] Number of results per page
         * @param {string} [name] Filter by partial name match
         * @param {ListSavedImagesSortEnum} [sort] Field to sort by
         * @param {ListSavedImagesOrderEnum} [order] Direction to sort by
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        listSavedImages(xBoxLiteOrganizationID?: string, page?: number, limit?: number, name?: string, sort?: ListSavedImagesSortEnum, order?: ListSavedImagesOrderEnum, options?: RawAxiosRequestConfig): AxiosPromise<Array<SavedImageDto> | PaginatedSavedImages> {
            return localVarFp.listSavedImages(xBoxLiteOrganizationID, page, limit, name, sort, order, options).then((request) => request(axios, basePath));
        },
        /**
         *
         * @summary Delete box savedImage
         * @param {string} id SavedImage ID
         * @param {string} [xBoxLiteOrganizationID] Use with JWT to specify the organization ID
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        removeSavedImage(id: string, xBoxLiteOrganizationID?: string, options?: RawAxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.removeSavedImage(id, xBoxLiteOrganizationID, options).then((request) => request(axios, basePath));
        },
        /**
         *
         * @summary Set box savedImage general status
         * @param {string} id SavedImage ID
         * @param {SetSavedImageGeneralStatus} setSavedImageGeneralStatus
         * @param {string} [xBoxLiteOrganizationID] Use with JWT to specify the organization ID
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        setSavedImageGeneralStatus(id: string, setSavedImageGeneralStatus: SetSavedImageGeneralStatus, xBoxLiteOrganizationID?: string, options?: RawAxiosRequestConfig): AxiosPromise<SavedImageDto> {
            return localVarFp.setSavedImageGeneralStatus(id, setSavedImageGeneralStatus, xBoxLiteOrganizationID, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * SavedImagesApi - object-oriented interface
 * @export
 * @class SavedImagesApi
 * @extends {BaseAPI}
 */
export class SavedImagesApi extends BaseAPI {
    /**
     *
     * @summary Activate a box savedImage
     * @param {string} id SavedImage ID
     * @param {string} [xBoxLiteOrganizationID] Use with JWT to specify the organization ID
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof SavedImagesApi
     */
    public activateSavedImage(id: string, xBoxLiteOrganizationID?: string, options?: RawAxiosRequestConfig) {
        return SavedImagesApiFp(this.configuration).activateSavedImage(id, xBoxLiteOrganizationID, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     *
     * @summary Create a new box savedImage
     * @param {CreateSavedImage} createSavedImage
     * @param {string} [xBoxLiteOrganizationID] Use with JWT to specify the organization ID
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof SavedImagesApi
     */
    public createSavedImage(createSavedImage: CreateSavedImage, xBoxLiteOrganizationID?: string, options?: RawAxiosRequestConfig) {
        return SavedImagesApiFp(this.configuration).createSavedImage(createSavedImage, xBoxLiteOrganizationID, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     *
     * @summary Deactivate a box savedImage
     * @param {string} id SavedImage ID
     * @param {string} [xBoxLiteOrganizationID] Use with JWT to specify the organization ID
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof SavedImagesApi
     */
    public deactivateSavedImage(id: string, xBoxLiteOrganizationID?: string, options?: RawAxiosRequestConfig) {
        return SavedImagesApiFp(this.configuration).deactivateSavedImage(id, xBoxLiteOrganizationID, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     *
     * @summary Get box savedImage by ID or name
     * @param {string} id SavedImage ID or name
     * @param {string} [xBoxLiteOrganizationID] Use with JWT to specify the organization ID
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof SavedImagesApi
     */
    public getSavedImage(id: string, xBoxLiteOrganizationID?: string, options?: RawAxiosRequestConfig) {
        return SavedImagesApiFp(this.configuration).getSavedImage(id, xBoxLiteOrganizationID, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * This endpoint is deprecated. Use `getSavedImageBuildLogsUrl` instead.
     * @summary Get box savedImage build logs
     * @param {string} id SavedImage ID
     * @param {string} [xBoxLiteOrganizationID] Use with JWT to specify the organization ID
     * @param {boolean} [follow] Whether to follow the logs stream
     * @param {*} [options] Override http request option.
     * @deprecated
     * @throws {RequiredError}
     * @memberof SavedImagesApi
     */
    public getSavedImageBuildLogs(id: string, xBoxLiteOrganizationID?: string, follow?: boolean, options?: RawAxiosRequestConfig) {
        return SavedImagesApiFp(this.configuration).getSavedImageBuildLogs(id, xBoxLiteOrganizationID, follow, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     *
     * @summary Get box savedImage build logs URL
     * @param {string} id SavedImage ID
     * @param {string} [xBoxLiteOrganizationID] Use with JWT to specify the organization ID
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof SavedImagesApi
     */
    public getSavedImageBuildLogsUrl(id: string, xBoxLiteOrganizationID?: string, options?: RawAxiosRequestConfig) {
        return SavedImagesApiFp(this.configuration).getSavedImageBuildLogsUrl(id, xBoxLiteOrganizationID, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     *
     * @summary List box savedImages
     * @param {string} [xBoxLiteOrganizationID] Use with JWT to specify the organization ID
     * @param {number} [page] Page number of the results
     * @param {number} [limit] Number of results per page
     * @param {string} [name] Filter by partial name match
     * @param {ListSavedImagesSortEnum} [sort] Field to sort by
     * @param {ListSavedImagesOrderEnum} [order] Direction to sort by
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof SavedImagesApi
     */
    public listSavedImages(xBoxLiteOrganizationID?: string, page?: number, limit?: number, name?: string, sort?: ListSavedImagesSortEnum, order?: ListSavedImagesOrderEnum, options?: RawAxiosRequestConfig) {
        return SavedImagesApiFp(this.configuration).listSavedImages(xBoxLiteOrganizationID, page, limit, name, sort, order, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     *
     * @summary Delete box savedImage
     * @param {string} id SavedImage ID
     * @param {string} [xBoxLiteOrganizationID] Use with JWT to specify the organization ID
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof SavedImagesApi
     */
    public removeSavedImage(id: string, xBoxLiteOrganizationID?: string, options?: RawAxiosRequestConfig) {
        return SavedImagesApiFp(this.configuration).removeSavedImage(id, xBoxLiteOrganizationID, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     *
     * @summary Set box savedImage general status
     * @param {string} id SavedImage ID
     * @param {SetSavedImageGeneralStatus} setSavedImageGeneralStatus
     * @param {string} [xBoxLiteOrganizationID] Use with JWT to specify the organization ID
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof SavedImagesApi
     */
    public setSavedImageGeneralStatus(id: string, setSavedImageGeneralStatus: SetSavedImageGeneralStatus, xBoxLiteOrganizationID?: string, options?: RawAxiosRequestConfig) {
        return SavedImagesApiFp(this.configuration).setSavedImageGeneralStatus(id, setSavedImageGeneralStatus, xBoxLiteOrganizationID, options).then((request) => request(this.axios, this.basePath));
    }
}

/**
 * @export
 */
export const ListSavedImagesSortEnum = {
    NAME: 'name',
    STATE: 'state',
    LAST_USED_AT: 'lastUsedAt',
    CREATED_AT: 'createdAt'
} as const;
export type ListSavedImagesSortEnum = typeof ListSavedImagesSortEnum[keyof typeof ListSavedImagesSortEnum];
/**
 * @export
 */
export const ListSavedImagesOrderEnum = {
    ASC: 'asc',
    DESC: 'desc'
} as const;
export type ListSavedImagesOrderEnum = typeof ListSavedImagesOrderEnum[keyof typeof ListSavedImagesOrderEnum];
