/* tslint:disable */
/* eslint-disable */
/**
 * BoxLite
 * BoxLite AI platform API Docs
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@boxlite.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { Configuration } from '../configuration'
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios'
import globalAxios from 'axios'
// Some imports not used depending on template conditions
// @ts-ignore
import {
  DUMMY_BASE_URL,
  assertParamExists,
  setApiKeyToObject,
  setBasicAuthToObject,
  setBearerAuthToObject,
  setOAuthToObject,
  setSearchParams,
  serializeDataIfNeeded,
  toPathString,
  createRequestFunction,
} from '../common'
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, type RequestArgs, BaseAPI, RequiredError, operationServerMap } from '../base'
// @ts-ignore
import type { BoxTemplateDto } from '../models'
// @ts-ignore
import type { CreateBoxTemplate } from '../models'
// @ts-ignore
import type { SetBoxTemplateGeneralStatus } from '../models'
// @ts-ignore
import type { Url } from '../models'
/**
 * TemplatesApi - axios parameter creator
 * @export
 */
export const TemplatesApiAxiosParamCreator = function (configuration?: Configuration) {
  return {
    /**
     *
     * @summary Activate a box template
     * @param {string} id Template ID
     * @param {string} [xBoxLiteOrganizationID] Use with JWT to specify the organization ID
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    activateBoxTemplate: async (
      id: string,
      xBoxLiteOrganizationID?: string,
      options: RawAxiosRequestConfig = {},
    ): Promise<RequestArgs> => {
      // verify required parameter 'id' is not null or undefined
      assertParamExists('activateBoxTemplate', 'id', id)
      const localVarPath = `/templates/{id}/activate`.replace(`{${'id'}}`, encodeURIComponent(String(id)))
      // use dummy base URL string because the URL constructor only accepts absolute URLs.
      const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL)
      let baseOptions
      if (configuration) {
        baseOptions = configuration.baseOptions
      }

      const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options }
      const localVarHeaderParameter = {} as any
      const localVarQueryParameter = {} as any

      // authentication bearer required
      // http bearer authentication required
      await setBearerAuthToObject(localVarHeaderParameter, configuration)

      // authentication oauth2 required

      if (xBoxLiteOrganizationID != null) {
        localVarHeaderParameter['X-BoxLite-Organization-ID'] = String(xBoxLiteOrganizationID)
      }
      setSearchParams(localVarUrlObj, localVarQueryParameter)
      let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {}
      localVarRequestOptions.headers = { ...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers }

      return {
        url: toPathString(localVarUrlObj),
        options: localVarRequestOptions,
      }
    },
    /**
     *
     * @summary Create a new box template
     * @param {CreateBoxTemplate} createBoxTemplate
     * @param {string} [xBoxLiteOrganizationID] Use with JWT to specify the organization ID
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    createBoxTemplate: async (
      createBoxTemplate: CreateBoxTemplate,
      xBoxLiteOrganizationID?: string,
      options: RawAxiosRequestConfig = {},
    ): Promise<RequestArgs> => {
      // verify required parameter 'createBoxTemplate' is not null or undefined
      assertParamExists('createBoxTemplate', 'createBoxTemplate', createBoxTemplate)
      const localVarPath = `/templates`
      // use dummy base URL string because the URL constructor only accepts absolute URLs.
      const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL)
      let baseOptions
      if (configuration) {
        baseOptions = configuration.baseOptions
      }

      const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options }
      const localVarHeaderParameter = {} as any
      const localVarQueryParameter = {} as any

      // authentication bearer required
      // http bearer authentication required
      await setBearerAuthToObject(localVarHeaderParameter, configuration)

      // authentication oauth2 required

      localVarHeaderParameter['Content-Type'] = 'application/json'

      if (xBoxLiteOrganizationID != null) {
        localVarHeaderParameter['X-BoxLite-Organization-ID'] = String(xBoxLiteOrganizationID)
      }
      setSearchParams(localVarUrlObj, localVarQueryParameter)
      let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {}
      localVarRequestOptions.headers = { ...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers }
      localVarRequestOptions.data = serializeDataIfNeeded(createBoxTemplate, localVarRequestOptions, configuration)

      return {
        url: toPathString(localVarUrlObj),
        options: localVarRequestOptions,
      }
    },
    /**
     *
     * @summary Deactivate a box template
     * @param {string} id Template ID
     * @param {string} [xBoxLiteOrganizationID] Use with JWT to specify the organization ID
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    deactivateBoxTemplate: async (
      id: string,
      xBoxLiteOrganizationID?: string,
      options: RawAxiosRequestConfig = {},
    ): Promise<RequestArgs> => {
      // verify required parameter 'id' is not null or undefined
      assertParamExists('deactivateBoxTemplate', 'id', id)
      const localVarPath = `/templates/{id}/deactivate`.replace(`{${'id'}}`, encodeURIComponent(String(id)))
      // use dummy base URL string because the URL constructor only accepts absolute URLs.
      const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL)
      let baseOptions
      if (configuration) {
        baseOptions = configuration.baseOptions
      }

      const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options }
      const localVarHeaderParameter = {} as any
      const localVarQueryParameter = {} as any

      // authentication bearer required
      // http bearer authentication required
      await setBearerAuthToObject(localVarHeaderParameter, configuration)

      // authentication oauth2 required

      if (xBoxLiteOrganizationID != null) {
        localVarHeaderParameter['X-BoxLite-Organization-ID'] = String(xBoxLiteOrganizationID)
      }
      setSearchParams(localVarUrlObj, localVarQueryParameter)
      let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {}
      localVarRequestOptions.headers = { ...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers }

      return {
        url: toPathString(localVarUrlObj),
        options: localVarRequestOptions,
      }
    },
    /**
     *
     * @summary Get box template by ID or name
     * @param {string} id Template ID or name
     * @param {string} [xBoxLiteOrganizationID] Use with JWT to specify the organization ID
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    getBoxTemplate: async (
      id: string,
      xBoxLiteOrganizationID?: string,
      options: RawAxiosRequestConfig = {},
    ): Promise<RequestArgs> => {
      // verify required parameter 'id' is not null or undefined
      assertParamExists('getBoxTemplate', 'id', id)
      const localVarPath = `/templates/{id}`.replace(`{${'id'}}`, encodeURIComponent(String(id)))
      // use dummy base URL string because the URL constructor only accepts absolute URLs.
      const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL)
      let baseOptions
      if (configuration) {
        baseOptions = configuration.baseOptions
      }

      const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options }
      const localVarHeaderParameter = {} as any
      const localVarQueryParameter = {} as any

      // authentication bearer required
      // http bearer authentication required
      await setBearerAuthToObject(localVarHeaderParameter, configuration)

      // authentication oauth2 required

      if (xBoxLiteOrganizationID != null) {
        localVarHeaderParameter['X-BoxLite-Organization-ID'] = String(xBoxLiteOrganizationID)
      }
      setSearchParams(localVarUrlObj, localVarQueryParameter)
      let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {}
      localVarRequestOptions.headers = { ...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers }

      return {
        url: toPathString(localVarUrlObj),
        options: localVarRequestOptions,
      }
    },
    /**
     * This endpoint is deprecated. Use `getBoxTemplateBuildLogsUrl` instead.
     * @summary Get box template build logs
     * @param {string} id Template ID
     * @param {string} [xBoxLiteOrganizationID] Use with JWT to specify the organization ID
     * @param {boolean} [follow] Whether to follow the logs stream
     * @param {*} [options] Override http request option.
     * @deprecated
     * @throws {RequiredError}
     */
    getBoxTemplateBuildLogs: async (
      id: string,
      xBoxLiteOrganizationID?: string,
      follow?: boolean,
      options: RawAxiosRequestConfig = {},
    ): Promise<RequestArgs> => {
      // verify required parameter 'id' is not null or undefined
      assertParamExists('getBoxTemplateBuildLogs', 'id', id)
      const localVarPath = `/templates/{id}/build-logs`.replace(`{${'id'}}`, encodeURIComponent(String(id)))
      // use dummy base URL string because the URL constructor only accepts absolute URLs.
      const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL)
      let baseOptions
      if (configuration) {
        baseOptions = configuration.baseOptions
      }

      const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options }
      const localVarHeaderParameter = {} as any
      const localVarQueryParameter = {} as any

      // authentication bearer required
      // http bearer authentication required
      await setBearerAuthToObject(localVarHeaderParameter, configuration)

      // authentication oauth2 required

      if (follow !== undefined) {
        localVarQueryParameter['follow'] = follow
      }

      if (xBoxLiteOrganizationID != null) {
        localVarHeaderParameter['X-BoxLite-Organization-ID'] = String(xBoxLiteOrganizationID)
      }
      setSearchParams(localVarUrlObj, localVarQueryParameter)
      let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {}
      localVarRequestOptions.headers = { ...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers }

      return {
        url: toPathString(localVarUrlObj),
        options: localVarRequestOptions,
      }
    },
    /**
     *
     * @summary Get box template build logs URL
     * @param {string} id Template ID
     * @param {string} [xBoxLiteOrganizationID] Use with JWT to specify the organization ID
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    getBoxTemplateBuildLogsUrl: async (
      id: string,
      xBoxLiteOrganizationID?: string,
      options: RawAxiosRequestConfig = {},
    ): Promise<RequestArgs> => {
      // verify required parameter 'id' is not null or undefined
      assertParamExists('getBoxTemplateBuildLogsUrl', 'id', id)
      const localVarPath = `/templates/{id}/build-logs-url`.replace(`{${'id'}}`, encodeURIComponent(String(id)))
      // use dummy base URL string because the URL constructor only accepts absolute URLs.
      const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL)
      let baseOptions
      if (configuration) {
        baseOptions = configuration.baseOptions
      }

      const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options }
      const localVarHeaderParameter = {} as any
      const localVarQueryParameter = {} as any

      // authentication bearer required
      // http bearer authentication required
      await setBearerAuthToObject(localVarHeaderParameter, configuration)

      // authentication oauth2 required

      if (xBoxLiteOrganizationID != null) {
        localVarHeaderParameter['X-BoxLite-Organization-ID'] = String(xBoxLiteOrganizationID)
      }
      setSearchParams(localVarUrlObj, localVarQueryParameter)
      let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {}
      localVarRequestOptions.headers = { ...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers }

      return {
        url: toPathString(localVarUrlObj),
        options: localVarRequestOptions,
      }
    },
    /**
     *
     * @summary List box templates
     * @param {string} [xBoxLiteOrganizationID] Use with JWT to specify the organization ID
     * @param {number} [page] Page number of the results
     * @param {number} [limit] Number of results per page
     * @param {string} [name] Filter by partial name match
     * @param {ListBoxTemplatesSortEnum} [sort] Field to sort by
     * @param {ListBoxTemplatesOrderEnum} [order] Direction to sort by
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    listBoxTemplates: async (
      xBoxLiteOrganizationID?: string,
      page?: number,
      limit?: number,
      name?: string,
      sort?: ListBoxTemplatesSortEnum,
      order?: ListBoxTemplatesOrderEnum,
      options: RawAxiosRequestConfig = {},
    ): Promise<RequestArgs> => {
      const localVarPath = `/templates`
      // use dummy base URL string because the URL constructor only accepts absolute URLs.
      const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL)
      let baseOptions
      if (configuration) {
        baseOptions = configuration.baseOptions
      }

      const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options }
      const localVarHeaderParameter = {} as any
      const localVarQueryParameter = {} as any

      // authentication bearer required
      // http bearer authentication required
      await setBearerAuthToObject(localVarHeaderParameter, configuration)

      // authentication oauth2 required

      if (page !== undefined) {
        localVarQueryParameter['page'] = page
      }

      if (limit !== undefined) {
        localVarQueryParameter['limit'] = limit
      }

      if (name !== undefined) {
        localVarQueryParameter['name'] = name
      }

      if (sort !== undefined) {
        localVarQueryParameter['sort'] = sort
      }

      if (order !== undefined) {
        localVarQueryParameter['order'] = order
      }

      if (xBoxLiteOrganizationID != null) {
        localVarHeaderParameter['X-BoxLite-Organization-ID'] = String(xBoxLiteOrganizationID)
      }
      setSearchParams(localVarUrlObj, localVarQueryParameter)
      let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {}
      localVarRequestOptions.headers = { ...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers }

      return {
        url: toPathString(localVarUrlObj),
        options: localVarRequestOptions,
      }
    },
    /**
     *
     * @summary Delete box template
     * @param {string} id Template ID
     * @param {string} [xBoxLiteOrganizationID] Use with JWT to specify the organization ID
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    removeBoxTemplate: async (
      id: string,
      xBoxLiteOrganizationID?: string,
      options: RawAxiosRequestConfig = {},
    ): Promise<RequestArgs> => {
      // verify required parameter 'id' is not null or undefined
      assertParamExists('removeBoxTemplate', 'id', id)
      const localVarPath = `/templates/{id}`.replace(`{${'id'}}`, encodeURIComponent(String(id)))
      // use dummy base URL string because the URL constructor only accepts absolute URLs.
      const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL)
      let baseOptions
      if (configuration) {
        baseOptions = configuration.baseOptions
      }

      const localVarRequestOptions = { method: 'DELETE', ...baseOptions, ...options }
      const localVarHeaderParameter = {} as any
      const localVarQueryParameter = {} as any

      // authentication bearer required
      // http bearer authentication required
      await setBearerAuthToObject(localVarHeaderParameter, configuration)

      // authentication oauth2 required

      if (xBoxLiteOrganizationID != null) {
        localVarHeaderParameter['X-BoxLite-Organization-ID'] = String(xBoxLiteOrganizationID)
      }
      setSearchParams(localVarUrlObj, localVarQueryParameter)
      let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {}
      localVarRequestOptions.headers = { ...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers }

      return {
        url: toPathString(localVarUrlObj),
        options: localVarRequestOptions,
      }
    },
    /**
     *
     * @summary Set box template general status
     * @param {string} id Template ID
     * @param {SetBoxTemplateGeneralStatus} setBoxTemplateGeneralStatus
     * @param {string} [xBoxLiteOrganizationID] Use with JWT to specify the organization ID
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    setBoxTemplateGeneralStatus: async (
      id: string,
      setBoxTemplateGeneralStatus: SetBoxTemplateGeneralStatus,
      xBoxLiteOrganizationID?: string,
      options: RawAxiosRequestConfig = {},
    ): Promise<RequestArgs> => {
      // verify required parameter 'id' is not null or undefined
      assertParamExists('setBoxTemplateGeneralStatus', 'id', id)
      // verify required parameter 'setBoxTemplateGeneralStatus' is not null or undefined
      assertParamExists('setBoxTemplateGeneralStatus', 'setBoxTemplateGeneralStatus', setBoxTemplateGeneralStatus)
      const localVarPath = `/templates/{id}/general`.replace(`{${'id'}}`, encodeURIComponent(String(id)))
      // use dummy base URL string because the URL constructor only accepts absolute URLs.
      const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL)
      let baseOptions
      if (configuration) {
        baseOptions = configuration.baseOptions
      }

      const localVarRequestOptions = { method: 'PATCH', ...baseOptions, ...options }
      const localVarHeaderParameter = {} as any
      const localVarQueryParameter = {} as any

      // authentication bearer required
      // http bearer authentication required
      await setBearerAuthToObject(localVarHeaderParameter, configuration)

      // authentication oauth2 required

      localVarHeaderParameter['Content-Type'] = 'application/json'

      if (xBoxLiteOrganizationID != null) {
        localVarHeaderParameter['X-BoxLite-Organization-ID'] = String(xBoxLiteOrganizationID)
      }
      setSearchParams(localVarUrlObj, localVarQueryParameter)
      let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {}
      localVarRequestOptions.headers = { ...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers }
      localVarRequestOptions.data = serializeDataIfNeeded(
        setBoxTemplateGeneralStatus,
        localVarRequestOptions,
        configuration,
      )

      return {
        url: toPathString(localVarUrlObj),
        options: localVarRequestOptions,
      }
    },
  }
}

/**
 * TemplatesApi - functional programming interface
 * @export
 */
export const TemplatesApiFp = function (configuration?: Configuration) {
  const localVarAxiosParamCreator = TemplatesApiAxiosParamCreator(configuration)
  return {
    /**
     *
     * @summary Activate a box template
     * @param {string} id Template ID
     * @param {string} [xBoxLiteOrganizationID] Use with JWT to specify the organization ID
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    async activateBoxTemplate(
      id: string,
      xBoxLiteOrganizationID?: string,
      options?: RawAxiosRequestConfig,
    ): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<BoxTemplateDto>> {
      const localVarAxiosArgs = await localVarAxiosParamCreator.activateBoxTemplate(id, xBoxLiteOrganizationID, options)
      const localVarOperationServerIndex = configuration?.serverIndex ?? 0
      const localVarOperationServerBasePath =
        operationServerMap['TemplatesApi.activateBoxTemplate']?.[localVarOperationServerIndex]?.url
      return (axios, basePath) =>
        createRequestFunction(
          localVarAxiosArgs,
          globalAxios,
          BASE_PATH,
          configuration,
        )(axios, localVarOperationServerBasePath || basePath)
    },
    /**
     *
     * @summary Create a new box template
     * @param {CreateBoxTemplate} createBoxTemplate
     * @param {string} [xBoxLiteOrganizationID] Use with JWT to specify the organization ID
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    async createBoxTemplate(
      createBoxTemplate: CreateBoxTemplate,
      xBoxLiteOrganizationID?: string,
      options?: RawAxiosRequestConfig,
    ): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<BoxTemplateDto>> {
      const localVarAxiosArgs = await localVarAxiosParamCreator.createBoxTemplate(
        createBoxTemplate,
        xBoxLiteOrganizationID,
        options,
      )
      const localVarOperationServerIndex = configuration?.serverIndex ?? 0
      const localVarOperationServerBasePath =
        operationServerMap['TemplatesApi.createBoxTemplate']?.[localVarOperationServerIndex]?.url
      return (axios, basePath) =>
        createRequestFunction(
          localVarAxiosArgs,
          globalAxios,
          BASE_PATH,
          configuration,
        )(axios, localVarOperationServerBasePath || basePath)
    },
    /**
     *
     * @summary Deactivate a box template
     * @param {string} id Template ID
     * @param {string} [xBoxLiteOrganizationID] Use with JWT to specify the organization ID
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    async deactivateBoxTemplate(
      id: string,
      xBoxLiteOrganizationID?: string,
      options?: RawAxiosRequestConfig,
    ): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
      const localVarAxiosArgs = await localVarAxiosParamCreator.deactivateBoxTemplate(
        id,
        xBoxLiteOrganizationID,
        options,
      )
      const localVarOperationServerIndex = configuration?.serverIndex ?? 0
      const localVarOperationServerBasePath =
        operationServerMap['TemplatesApi.deactivateBoxTemplate']?.[localVarOperationServerIndex]?.url
      return (axios, basePath) =>
        createRequestFunction(
          localVarAxiosArgs,
          globalAxios,
          BASE_PATH,
          configuration,
        )(axios, localVarOperationServerBasePath || basePath)
    },
    /**
     *
     * @summary Get box template by ID or name
     * @param {string} id Template ID or name
     * @param {string} [xBoxLiteOrganizationID] Use with JWT to specify the organization ID
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    async getBoxTemplate(
      id: string,
      xBoxLiteOrganizationID?: string,
      options?: RawAxiosRequestConfig,
    ): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<BoxTemplateDto>> {
      const localVarAxiosArgs = await localVarAxiosParamCreator.getBoxTemplate(id, xBoxLiteOrganizationID, options)
      const localVarOperationServerIndex = configuration?.serverIndex ?? 0
      const localVarOperationServerBasePath =
        operationServerMap['TemplatesApi.getBoxTemplate']?.[localVarOperationServerIndex]?.url
      return (axios, basePath) =>
        createRequestFunction(
          localVarAxiosArgs,
          globalAxios,
          BASE_PATH,
          configuration,
        )(axios, localVarOperationServerBasePath || basePath)
    },
    /**
     * This endpoint is deprecated. Use `getBoxTemplateBuildLogsUrl` instead.
     * @summary Get box template build logs
     * @param {string} id Template ID
     * @param {string} [xBoxLiteOrganizationID] Use with JWT to specify the organization ID
     * @param {boolean} [follow] Whether to follow the logs stream
     * @param {*} [options] Override http request option.
     * @deprecated
     * @throws {RequiredError}
     */
    async getBoxTemplateBuildLogs(
      id: string,
      xBoxLiteOrganizationID?: string,
      follow?: boolean,
      options?: RawAxiosRequestConfig,
    ): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
      const localVarAxiosArgs = await localVarAxiosParamCreator.getBoxTemplateBuildLogs(
        id,
        xBoxLiteOrganizationID,
        follow,
        options,
      )
      const localVarOperationServerIndex = configuration?.serverIndex ?? 0
      const localVarOperationServerBasePath =
        operationServerMap['TemplatesApi.getBoxTemplateBuildLogs']?.[localVarOperationServerIndex]?.url
      return (axios, basePath) =>
        createRequestFunction(
          localVarAxiosArgs,
          globalAxios,
          BASE_PATH,
          configuration,
        )(axios, localVarOperationServerBasePath || basePath)
    },
    /**
     *
     * @summary Get box template build logs URL
     * @param {string} id Template ID
     * @param {string} [xBoxLiteOrganizationID] Use with JWT to specify the organization ID
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    async getBoxTemplateBuildLogsUrl(
      id: string,
      xBoxLiteOrganizationID?: string,
      options?: RawAxiosRequestConfig,
    ): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Url>> {
      const localVarAxiosArgs = await localVarAxiosParamCreator.getBoxTemplateBuildLogsUrl(
        id,
        xBoxLiteOrganizationID,
        options,
      )
      const localVarOperationServerIndex = configuration?.serverIndex ?? 0
      const localVarOperationServerBasePath =
        operationServerMap['TemplatesApi.getBoxTemplateBuildLogsUrl']?.[localVarOperationServerIndex]?.url
      return (axios, basePath) =>
        createRequestFunction(
          localVarAxiosArgs,
          globalAxios,
          BASE_PATH,
          configuration,
        )(axios, localVarOperationServerBasePath || basePath)
    },
    /**
     *
     * @summary List box templates
     * @param {string} [xBoxLiteOrganizationID] Use with JWT to specify the organization ID
     * @param {number} [page] Page number of the results
     * @param {number} [limit] Number of results per page
     * @param {string} [name] Filter by partial name match
     * @param {ListBoxTemplatesSortEnum} [sort] Field to sort by
     * @param {ListBoxTemplatesOrderEnum} [order] Direction to sort by
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    async listBoxTemplates(
      xBoxLiteOrganizationID?: string,
      page?: number,
      limit?: number,
      name?: string,
      sort?: ListBoxTemplatesSortEnum,
      order?: ListBoxTemplatesOrderEnum,
      options?: RawAxiosRequestConfig,
    ): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Array<BoxTemplateDto>>> {
      const localVarAxiosArgs = await localVarAxiosParamCreator.listBoxTemplates(
        xBoxLiteOrganizationID,
        page,
        limit,
        name,
        sort,
        order,
        options,
      )
      const localVarOperationServerIndex = configuration?.serverIndex ?? 0
      const localVarOperationServerBasePath =
        operationServerMap['TemplatesApi.listBoxTemplates']?.[localVarOperationServerIndex]?.url
      return (axios, basePath) =>
        createRequestFunction(
          localVarAxiosArgs,
          globalAxios,
          BASE_PATH,
          configuration,
        )(axios, localVarOperationServerBasePath || basePath)
    },
    /**
     *
     * @summary Delete box template
     * @param {string} id Template ID
     * @param {string} [xBoxLiteOrganizationID] Use with JWT to specify the organization ID
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    async removeBoxTemplate(
      id: string,
      xBoxLiteOrganizationID?: string,
      options?: RawAxiosRequestConfig,
    ): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
      const localVarAxiosArgs = await localVarAxiosParamCreator.removeBoxTemplate(id, xBoxLiteOrganizationID, options)
      const localVarOperationServerIndex = configuration?.serverIndex ?? 0
      const localVarOperationServerBasePath =
        operationServerMap['TemplatesApi.removeBoxTemplate']?.[localVarOperationServerIndex]?.url
      return (axios, basePath) =>
        createRequestFunction(
          localVarAxiosArgs,
          globalAxios,
          BASE_PATH,
          configuration,
        )(axios, localVarOperationServerBasePath || basePath)
    },
    /**
     *
     * @summary Set box template general status
     * @param {string} id Template ID
     * @param {SetBoxTemplateGeneralStatus} setBoxTemplateGeneralStatus
     * @param {string} [xBoxLiteOrganizationID] Use with JWT to specify the organization ID
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    async setBoxTemplateGeneralStatus(
      id: string,
      setBoxTemplateGeneralStatus: SetBoxTemplateGeneralStatus,
      xBoxLiteOrganizationID?: string,
      options?: RawAxiosRequestConfig,
    ): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<BoxTemplateDto>> {
      const localVarAxiosArgs = await localVarAxiosParamCreator.setBoxTemplateGeneralStatus(
        id,
        setBoxTemplateGeneralStatus,
        xBoxLiteOrganizationID,
        options,
      )
      const localVarOperationServerIndex = configuration?.serverIndex ?? 0
      const localVarOperationServerBasePath =
        operationServerMap['TemplatesApi.setBoxTemplateGeneralStatus']?.[localVarOperationServerIndex]?.url
      return (axios, basePath) =>
        createRequestFunction(
          localVarAxiosArgs,
          globalAxios,
          BASE_PATH,
          configuration,
        )(axios, localVarOperationServerBasePath || basePath)
    },
  }
}

/**
 * TemplatesApi - factory interface
 * @export
 */
export const TemplatesApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
  const localVarFp = TemplatesApiFp(configuration)
  return {
    /**
     *
     * @summary Activate a box template
     * @param {string} id Template ID
     * @param {string} [xBoxLiteOrganizationID] Use with JWT to specify the organization ID
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    activateBoxTemplate(
      id: string,
      xBoxLiteOrganizationID?: string,
      options?: RawAxiosRequestConfig,
    ): AxiosPromise<BoxTemplateDto> {
      return localVarFp
        .activateBoxTemplate(id, xBoxLiteOrganizationID, options)
        .then((request) => request(axios, basePath))
    },
    /**
     *
     * @summary Create a new box template
     * @param {CreateBoxTemplate} createBoxTemplate
     * @param {string} [xBoxLiteOrganizationID] Use with JWT to specify the organization ID
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    createBoxTemplate(
      createBoxTemplate: CreateBoxTemplate,
      xBoxLiteOrganizationID?: string,
      options?: RawAxiosRequestConfig,
    ): AxiosPromise<BoxTemplateDto> {
      return localVarFp
        .createBoxTemplate(createBoxTemplate, xBoxLiteOrganizationID, options)
        .then((request) => request(axios, basePath))
    },
    /**
     *
     * @summary Deactivate a box template
     * @param {string} id Template ID
     * @param {string} [xBoxLiteOrganizationID] Use with JWT to specify the organization ID
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    deactivateBoxTemplate(
      id: string,
      xBoxLiteOrganizationID?: string,
      options?: RawAxiosRequestConfig,
    ): AxiosPromise<void> {
      return localVarFp
        .deactivateBoxTemplate(id, xBoxLiteOrganizationID, options)
        .then((request) => request(axios, basePath))
    },
    /**
     *
     * @summary Get box template by ID or name
     * @param {string} id Template ID or name
     * @param {string} [xBoxLiteOrganizationID] Use with JWT to specify the organization ID
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    getBoxTemplate(
      id: string,
      xBoxLiteOrganizationID?: string,
      options?: RawAxiosRequestConfig,
    ): AxiosPromise<BoxTemplateDto> {
      return localVarFp.getBoxTemplate(id, xBoxLiteOrganizationID, options).then((request) => request(axios, basePath))
    },
    /**
     * This endpoint is deprecated. Use `getBoxTemplateBuildLogsUrl` instead.
     * @summary Get box template build logs
     * @param {string} id Template ID
     * @param {string} [xBoxLiteOrganizationID] Use with JWT to specify the organization ID
     * @param {boolean} [follow] Whether to follow the logs stream
     * @param {*} [options] Override http request option.
     * @deprecated
     * @throws {RequiredError}
     */
    getBoxTemplateBuildLogs(
      id: string,
      xBoxLiteOrganizationID?: string,
      follow?: boolean,
      options?: RawAxiosRequestConfig,
    ): AxiosPromise<void> {
      return localVarFp
        .getBoxTemplateBuildLogs(id, xBoxLiteOrganizationID, follow, options)
        .then((request) => request(axios, basePath))
    },
    /**
     *
     * @summary Get box template build logs URL
     * @param {string} id Template ID
     * @param {string} [xBoxLiteOrganizationID] Use with JWT to specify the organization ID
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    getBoxTemplateBuildLogsUrl(
      id: string,
      xBoxLiteOrganizationID?: string,
      options?: RawAxiosRequestConfig,
    ): AxiosPromise<Url> {
      return localVarFp
        .getBoxTemplateBuildLogsUrl(id, xBoxLiteOrganizationID, options)
        .then((request) => request(axios, basePath))
    },
    /**
     *
     * @summary List box templates
     * @param {string} [xBoxLiteOrganizationID] Use with JWT to specify the organization ID
     * @param {number} [page] Page number of the results
     * @param {number} [limit] Number of results per page
     * @param {string} [name] Filter by partial name match
     * @param {ListBoxTemplatesSortEnum} [sort] Field to sort by
     * @param {ListBoxTemplatesOrderEnum} [order] Direction to sort by
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    listBoxTemplates(
      xBoxLiteOrganizationID?: string,
      page?: number,
      limit?: number,
      name?: string,
      sort?: ListBoxTemplatesSortEnum,
      order?: ListBoxTemplatesOrderEnum,
      options?: RawAxiosRequestConfig,
    ): AxiosPromise<Array<BoxTemplateDto>> {
      return localVarFp
        .listBoxTemplates(xBoxLiteOrganizationID, page, limit, name, sort, order, options)
        .then((request) => request(axios, basePath))
    },
    /**
     *
     * @summary Delete box template
     * @param {string} id Template ID
     * @param {string} [xBoxLiteOrganizationID] Use with JWT to specify the organization ID
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    removeBoxTemplate(
      id: string,
      xBoxLiteOrganizationID?: string,
      options?: RawAxiosRequestConfig,
    ): AxiosPromise<void> {
      return localVarFp
        .removeBoxTemplate(id, xBoxLiteOrganizationID, options)
        .then((request) => request(axios, basePath))
    },
    /**
     *
     * @summary Set box template general status
     * @param {string} id Template ID
     * @param {SetBoxTemplateGeneralStatus} setBoxTemplateGeneralStatus
     * @param {string} [xBoxLiteOrganizationID] Use with JWT to specify the organization ID
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    setBoxTemplateGeneralStatus(
      id: string,
      setBoxTemplateGeneralStatus: SetBoxTemplateGeneralStatus,
      xBoxLiteOrganizationID?: string,
      options?: RawAxiosRequestConfig,
    ): AxiosPromise<BoxTemplateDto> {
      return localVarFp
        .setBoxTemplateGeneralStatus(id, setBoxTemplateGeneralStatus, xBoxLiteOrganizationID, options)
        .then((request) => request(axios, basePath))
    },
  }
}

/**
 * TemplatesApi - object-oriented interface
 * @export
 * @class TemplatesApi
 * @extends {BaseAPI}
 */
export class TemplatesApi extends BaseAPI {
  /**
   *
   * @summary Activate a box template
   * @param {string} id Template ID
   * @param {string} [xBoxLiteOrganizationID] Use with JWT to specify the organization ID
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   * @memberof TemplatesApi
   */
  public activateBoxTemplate(id: string, xBoxLiteOrganizationID?: string, options?: RawAxiosRequestConfig) {
    return TemplatesApiFp(this.configuration)
      .activateBoxTemplate(id, xBoxLiteOrganizationID, options)
      .then((request) => request(this.axios, this.basePath))
  }

  /**
   *
   * @summary Create a new box template
   * @param {CreateBoxTemplate} createBoxTemplate
   * @param {string} [xBoxLiteOrganizationID] Use with JWT to specify the organization ID
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   * @memberof TemplatesApi
   */
  public createBoxTemplate(
    createBoxTemplate: CreateBoxTemplate,
    xBoxLiteOrganizationID?: string,
    options?: RawAxiosRequestConfig,
  ) {
    return TemplatesApiFp(this.configuration)
      .createBoxTemplate(createBoxTemplate, xBoxLiteOrganizationID, options)
      .then((request) => request(this.axios, this.basePath))
  }

  /**
   *
   * @summary Deactivate a box template
   * @param {string} id Template ID
   * @param {string} [xBoxLiteOrganizationID] Use with JWT to specify the organization ID
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   * @memberof TemplatesApi
   */
  public deactivateBoxTemplate(id: string, xBoxLiteOrganizationID?: string, options?: RawAxiosRequestConfig) {
    return TemplatesApiFp(this.configuration)
      .deactivateBoxTemplate(id, xBoxLiteOrganizationID, options)
      .then((request) => request(this.axios, this.basePath))
  }

  /**
   *
   * @summary Get box template by ID or name
   * @param {string} id Template ID or name
   * @param {string} [xBoxLiteOrganizationID] Use with JWT to specify the organization ID
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   * @memberof TemplatesApi
   */
  public getBoxTemplate(id: string, xBoxLiteOrganizationID?: string, options?: RawAxiosRequestConfig) {
    return TemplatesApiFp(this.configuration)
      .getBoxTemplate(id, xBoxLiteOrganizationID, options)
      .then((request) => request(this.axios, this.basePath))
  }

  /**
   * This endpoint is deprecated. Use `getBoxTemplateBuildLogsUrl` instead.
   * @summary Get box template build logs
   * @param {string} id Template ID
   * @param {string} [xBoxLiteOrganizationID] Use with JWT to specify the organization ID
   * @param {boolean} [follow] Whether to follow the logs stream
   * @param {*} [options] Override http request option.
   * @deprecated
   * @throws {RequiredError}
   * @memberof TemplatesApi
   */
  public getBoxTemplateBuildLogs(
    id: string,
    xBoxLiteOrganizationID?: string,
    follow?: boolean,
    options?: RawAxiosRequestConfig,
  ) {
    return TemplatesApiFp(this.configuration)
      .getBoxTemplateBuildLogs(id, xBoxLiteOrganizationID, follow, options)
      .then((request) => request(this.axios, this.basePath))
  }

  /**
   *
   * @summary Get box template build logs URL
   * @param {string} id Template ID
   * @param {string} [xBoxLiteOrganizationID] Use with JWT to specify the organization ID
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   * @memberof TemplatesApi
   */
  public getBoxTemplateBuildLogsUrl(id: string, xBoxLiteOrganizationID?: string, options?: RawAxiosRequestConfig) {
    return TemplatesApiFp(this.configuration)
      .getBoxTemplateBuildLogsUrl(id, xBoxLiteOrganizationID, options)
      .then((request) => request(this.axios, this.basePath))
  }

  /**
   *
   * @summary List box templates
   * @param {string} [xBoxLiteOrganizationID] Use with JWT to specify the organization ID
   * @param {number} [page] Page number of the results
   * @param {number} [limit] Number of results per page
   * @param {string} [name] Filter by partial name match
   * @param {ListBoxTemplatesSortEnum} [sort] Field to sort by
   * @param {ListBoxTemplatesOrderEnum} [order] Direction to sort by
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   * @memberof TemplatesApi
   */
  public listBoxTemplates(
    xBoxLiteOrganizationID?: string,
    page?: number,
    limit?: number,
    name?: string,
    sort?: ListBoxTemplatesSortEnum,
    order?: ListBoxTemplatesOrderEnum,
    options?: RawAxiosRequestConfig,
  ) {
    return TemplatesApiFp(this.configuration)
      .listBoxTemplates(xBoxLiteOrganizationID, page, limit, name, sort, order, options)
      .then((request) => request(this.axios, this.basePath))
  }

  /**
   *
   * @summary Delete box template
   * @param {string} id Template ID
   * @param {string} [xBoxLiteOrganizationID] Use with JWT to specify the organization ID
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   * @memberof TemplatesApi
   */
  public removeBoxTemplate(id: string, xBoxLiteOrganizationID?: string, options?: RawAxiosRequestConfig) {
    return TemplatesApiFp(this.configuration)
      .removeBoxTemplate(id, xBoxLiteOrganizationID, options)
      .then((request) => request(this.axios, this.basePath))
  }

  /**
   *
   * @summary Set box template general status
   * @param {string} id Template ID
   * @param {SetBoxTemplateGeneralStatus} setBoxTemplateGeneralStatus
   * @param {string} [xBoxLiteOrganizationID] Use with JWT to specify the organization ID
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   * @memberof TemplatesApi
   */
  public setBoxTemplateGeneralStatus(
    id: string,
    setBoxTemplateGeneralStatus: SetBoxTemplateGeneralStatus,
    xBoxLiteOrganizationID?: string,
    options?: RawAxiosRequestConfig,
  ) {
    return TemplatesApiFp(this.configuration)
      .setBoxTemplateGeneralStatus(id, setBoxTemplateGeneralStatus, xBoxLiteOrganizationID, options)
      .then((request) => request(this.axios, this.basePath))
  }
}

/**
 * @export
 */
export const ListBoxTemplatesSortEnum = {
  NAME: 'name',
  STATE: 'state',
  LAST_USED_AT: 'lastUsedAt',
  CREATED_AT: 'createdAt',
} as const
export type ListBoxTemplatesSortEnum = (typeof ListBoxTemplatesSortEnum)[keyof typeof ListBoxTemplatesSortEnum]
/**
 * @export
 */
export const ListBoxTemplatesOrderEnum = {
  ASC: 'asc',
  DESC: 'desc',
} as const
export type ListBoxTemplatesOrderEnum = (typeof ListBoxTemplatesOrderEnum)[keyof typeof ListBoxTemplatesOrderEnum]
