/* tslint:disable */
/* eslint-disable */
/**
 * BoxLite
 * BoxLite AI platform API Docs
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@boxlite.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 *
 * @export
 * @interface ArtifactRegistryCredentials
 */
export interface ArtifactRegistryCredentials {
    /**
     * Artifact Registry username for the region
     * @type {string}
     * @memberof ArtifactRegistryCredentials
     */
    'username': string;
    /**
     * Artifact Registry password for the region
     * @type {string}
     * @memberof ArtifactRegistryCredentials
     */
    'password': string;
}
