/* tslint:disable */
/* eslint-disable */
/**
 * BoxLite
 * BoxLite AI platform API Docs
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@boxlite.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

// May contain unused imports in some cases
// @ts-ignore
import type { BoxTemplateDefaultResourcesDto } from './box-template-default-resources-dto'
// May contain unused imports in some cases
// @ts-ignore
import type { BoxTemplateState } from './box-template-state'
// May contain unused imports in some cases
// @ts-ignore
import type { BuildInfo } from './build-info'

/**
 *
 * @export
 * @interface BoxTemplateDto
 */
export interface BoxTemplateDto {
  /**
   *
   * @type {string}
   * @memberof BoxTemplateDto
   */
  id: string
  /**
   *
   * @type {string}
   * @memberof BoxTemplateDto
   */
  organizationId?: string
  /**
   *
   * @type {boolean}
   * @memberof BoxTemplateDto
   */
  general: boolean
  /**
   *
   * @type {string}
   * @memberof BoxTemplateDto
   */
  name: string
  /**
   *
   * @type {string}
   * @memberof BoxTemplateDto
   */
  displayName: string
  /**
   *
   * @type {string}
   * @memberof BoxTemplateDto
   */
  description?: string
  /**
   * Agent/runtime capabilities included in this official image
   * @type {Array<string>}
   * @memberof BoxTemplateDto
   */
  capabilities?: Array<string>
  /**
   *
   * @type {string}
   * @memberof BoxTemplateDto
   */
  artifactRef?: string
  /**
   *
   * @type {BoxTemplateState}
   * @memberof BoxTemplateDto
   */
  state: BoxTemplateState
  /**
   *
   * @type {string}
   * @memberof BoxTemplateDto
   */
  errorReason?: string
  /**
   *
   * @type {BoxTemplateDefaultResourcesDto}
   * @memberof BoxTemplateDto
   */
  defaultResources: BoxTemplateDefaultResourcesDto
  /**
   *
   * @type {Date}
   * @memberof BoxTemplateDto
   */
  createdAt: Date
  /**
   *
   * @type {Date}
   * @memberof BoxTemplateDto
   */
  updatedAt: Date
  /**
   *
   * @type {Date}
   * @memberof BoxTemplateDto
   */
  lastUsedAt?: Date
  /**
   * Build information for this template
   * @type {BuildInfo}
   * @memberof BoxTemplateDto
   */
  buildInfo?: BuildInfo
  /**
   * The initial runner ID of the template
   * @type {string}
   * @memberof BoxTemplateDto
   */
  initialRunnerId?: string
  /**
   * IDs of regions where the template is available to this organization
   * @type {Array<string>}
   * @memberof BoxTemplateDto
   */
  regionIds?: Array<string>
}
