/* tslint:disable */
/* eslint-disable */
/**
 * BoxLite
 * BoxLite AI platform API Docs
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@boxlite.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface BoxTemplateDefaultResourcesDto
 */
export interface BoxTemplateDefaultResourcesDto {
  /**
   *
   * @type {number}
   * @memberof BoxTemplateDefaultResourcesDto
   */
  cpu: number
  /**
   *
   * @type {number}
   * @memberof BoxTemplateDefaultResourcesDto
   */
  gpu: number
  /**
   *
   * @type {number}
   * @memberof BoxTemplateDefaultResourcesDto
   */
  memory: number
  /**
   *
   * @type {number}
   * @memberof BoxTemplateDefaultResourcesDto
   */
  disk: number
}
