/* tslint:disable */
/* eslint-disable */
/**
 * BoxLite
 * BoxLite AI platform API Docs
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@boxlite.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface Box
 */
export interface Box {
  /**
   * The public 12-character Box ID shown to users and SDK clients
   * @type {string}
   * @memberof Box
   */
  boxId: string
  /**
   * User-provided box name
   * @type {string}
   * @memberof Box
   */
  name?: string
  /**
   * Box runtime status
   * @type {string}
   * @memberof Box
   */
  status: string
  /**
   * Creation timestamp
   * @type {string}
   * @memberof Box
   */
  createdAt: string
  /**
   * Last update timestamp
   * @type {string}
   * @memberof Box
   */
  updatedAt: string
  /**
   * Runtime process ID when available
   * @type {number}
   * @memberof Box
   */
  pid?: number
  /**
   * Approved image/template used for the box
   * @type {string}
   * @memberof Box
   */
  image: string
  /**
   * Allocated CPU count
   * @type {number}
   * @memberof Box
   */
  cpus: number
  /**
   * Allocated memory in MiB
   * @type {number}
   * @memberof Box
   */
  memoryMib: number
  /**
   * Labels attached to the box
   * @type {{ [key: string]: string; }}
   * @memberof Box
   */
  labels: { [key: string]: string }
}
