/* tslint:disable */
/* eslint-disable */
/**
 * BoxLite
 * BoxLite AI platform API Docs
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@boxlite.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { Announcement } from './announcement';
// May contain unused imports in some cases
// @ts-ignore
import type { OidcConfig } from './oidc-config';
// May contain unused imports in some cases
// @ts-ignore
import type { PosthogConfig } from './posthog-config';
// May contain unused imports in some cases
// @ts-ignore
import type { RateLimitConfig } from './rate-limit-config';

/**
 *
 * @export
 * @interface BoxliteConfiguration
 */
export interface BoxliteConfiguration {
    /**
     * BoxLite version
     * @type {string}
     * @memberof BoxliteConfiguration
     */
    'version': string;
    /**
     * PostHog configuration
     * @type {PosthogConfig}
     * @memberof BoxliteConfiguration
     */
    'posthog'?: PosthogConfig;
    /**
     * OIDC configuration
     * @type {OidcConfig}
     * @memberof BoxliteConfiguration
     */
    'oidc': OidcConfig;
    /**
     * Whether linked accounts are enabled
     * @type {boolean}
     * @memberof BoxliteConfiguration
     */
    'linkedAccountsEnabled': boolean;
    /**
     * System announcements
     * @type {{ [key: string]: Announcement; }}
     * @memberof BoxliteConfiguration
     */
    'announcements': { [key: string]: Announcement; };
    /**
     * Pylon application ID
     * @type {string}
     * @memberof BoxliteConfiguration
     */
    'pylonAppId'?: string;
    /**
     * Proxy savedImage URL
     * @type {string}
     * @memberof BoxliteConfiguration
     */
    'proxySavedImageUrl': string;
    /**
     * Toolbox savedImage URL
     * @type {string}
     * @memberof BoxliteConfiguration
     */
    'proxyToolboxUrl': string;
    /**
     * Default savedImage for sandboxes
     * @type {string}
     * @memberof BoxliteConfiguration
     */
    'defaultSavedImage': string;
    /**
     * Dashboard URL
     * @type {string}
     * @memberof BoxliteConfiguration
     */
    'dashboardUrl': string;
    /**
     * Maximum auto-archive interval in minutes
     * @type {number}
     * @memberof BoxliteConfiguration
     */
    'maxAutoArchiveInterval': number;
    /**
     * Whether maintenance mode is enabled
     * @type {boolean}
     * @memberof BoxliteConfiguration
     */
    'maintananceMode': boolean;
    /**
     * Current environment
     * @type {string}
     * @memberof BoxliteConfiguration
     */
    'environment': string;
    /**
     * Billing API URL
     * @type {string}
     * @memberof BoxliteConfiguration
     */
    'billingApiUrl'?: string;
    /**
     * Analytics API URL
     * @type {string}
     * @memberof BoxliteConfiguration
     */
    'analyticsApiUrl'?: string;
    /**
     * SSH Gateway command
     * @type {string}
     * @memberof BoxliteConfiguration
     */
    'sshGatewayCommand'?: string;
    /**
     * Base64 encoded SSH Gateway public key
     * @type {string}
     * @memberof BoxliteConfiguration
     */
    'sshGatewayPublicKey'?: string;
    /**
     * Rate limit configuration
     * @type {RateLimitConfig}
     * @memberof BoxliteConfiguration
     */
    'rateLimit'?: RateLimitConfig;
}
