/* tslint:disable */
/* eslint-disable */
/**
 * BoxLite
 * BoxLite AI platform API Docs
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@boxlite.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { CreateBuildInfo } from './create-build-info';

/**
 *
 * @export
 * @interface CreateSavedImage
 */
export interface CreateSavedImage {
    /**
     * The saved image name
     * @type {string}
     * @memberof CreateSavedImage
     */
    'name': string;
    /**
     * The source image used to create the saved image artifact
     * @type {string}
     * @memberof CreateSavedImage
     */
    'imageName'?: string;
    /**
     * The entrypoint command for boxes created from the savedImage
     * @type {Array<string>}
     * @memberof CreateSavedImage
     */
    'entrypoint'?: Array<string>;
    /**
     * Whether the saved image is available to all organizations
     * @type {boolean}
     * @memberof CreateSavedImage
     */
    'general'?: boolean;
    /**
     * Default CPU cores allocated to boxes created from the savedImage
     * @type {number}
     * @memberof CreateSavedImage
     */
    'cpu'?: number;
    /**
     * Default GPU units allocated to boxes created from the savedImage
     * @type {number}
     * @memberof CreateSavedImage
     */
    'gpu'?: number;
    /**
     * Default memory allocated to boxes created from the saved image in GB
     * @type {number}
     * @memberof CreateSavedImage
     */
    'memory'?: number;
    /**
     * Default disk allocated to boxes created from the saved image in GB
     * @type {number}
     * @memberof CreateSavedImage
     */
    'disk'?: number;
    /**
     * Build information for the saved image artifact
     * @type {CreateBuildInfo}
     * @memberof CreateSavedImage
     */
    'buildInfo'?: CreateBuildInfo;
    /**
     * ID of the region where the saved image will be available. Defaults to organization default region if not specified.
     * @type {string}
     * @memberof CreateSavedImage
     */
    'regionId'?: string;
}
