/* tslint:disable */
/* eslint-disable */
/**
 * BoxLite
 * BoxLite AI platform API Docs
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@boxlite.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

// May contain unused imports in some cases
// @ts-ignore
import type { CreateBuildInfo } from './create-build-info'

/**
 *
 * @export
 * @interface CreateBoxTemplate
 */
export interface CreateBoxTemplate {
  /**
   * The template name
   * @type {string}
   * @memberof CreateBoxTemplate
   */
  name: string
  /**
   * The source image used to create the template artifact
   * @type {string}
   * @memberof CreateBoxTemplate
   */
  imageName?: string
  /**
   * The entrypoint command for boxes created from the template
   * @type {Array<string>}
   * @memberof CreateBoxTemplate
   */
  entrypoint?: Array<string>
  /**
   * Whether the template is available to all organizations
   * @type {boolean}
   * @memberof CreateBoxTemplate
   */
  general?: boolean
  /**
   * Default CPU cores allocated to boxes created from the template
   * @type {number}
   * @memberof CreateBoxTemplate
   */
  cpu?: number
  /**
   * Default GPU units allocated to boxes created from the template
   * @type {number}
   * @memberof CreateBoxTemplate
   */
  gpu?: number
  /**
   * Default memory allocated to boxes created from the template in GB
   * @type {number}
   * @memberof CreateBoxTemplate
   */
  memory?: number
  /**
   * Default disk allocated to boxes created from the template in GB
   * @type {number}
   * @memberof CreateBoxTemplate
   */
  disk?: number
  /**
   * Build information for the template artifact
   * @type {CreateBuildInfo}
   * @memberof CreateBoxTemplate
   */
  buildInfo?: CreateBuildInfo
  /**
   * ID of the region where the template will be available. Defaults to organization default region if not specified.
   * @type {string}
   * @memberof CreateBoxTemplate
   */
  regionId?: string
}
