/* tslint:disable */
/* eslint-disable */
/**
 * BoxLite
 * BoxLite AI platform API Docs
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@boxlite.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 *
 * @export
 * @interface CreateRegionResponse
 */
export interface CreateRegionResponse {
    /**
     * ID of the created region
     * @type {string}
     * @memberof CreateRegionResponse
     */
    'id': string;
    /**
     * Proxy API key for the region
     * @type {string}
     * @memberof CreateRegionResponse
     */
    'proxyApiKey'?: string | null;
    /**
     * SSH Gateway API key for the region
     * @type {string}
     * @memberof CreateRegionResponse
     */
    'sshGatewayApiKey'?: string | null;
    /**
     * Artifact Registry username for the region
     * @type {string}
     * @memberof CreateRegionResponse
     */
    'artifactRegistryUsername'?: string | null;
    /**
     * Artifact Registry password for the region
     * @type {string}
     * @memberof CreateRegionResponse
     */
    'artifactRegistryPassword'?: string | null;
}
