/* tslint:disable */
/* eslint-disable */
/**
 * BoxLite
 * BoxLite AI platform API Docs
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@boxlite.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * The type of the job
 * @export
 * @enum {string}
 */

export const JobType = {
  CREATE_SANDBOX: 'CREATE_SANDBOX',
  START_SANDBOX: 'START_SANDBOX',
  STOP_SANDBOX: 'STOP_SANDBOX',
  DESTROY_SANDBOX: 'DESTROY_SANDBOX',
  RESIZE_SANDBOX: 'RESIZE_SANDBOX',
  CREATE_BACKUP: 'CREATE_BACKUP',
  BUILD_ARTIFACT: 'BUILD_ARTIFACT',
  PULL_ARTIFACT: 'PULL_ARTIFACT',
  RECOVER_SANDBOX: 'RECOVER_SANDBOX',
  INSPECT_ARTIFACT_IN_REGISTRY: 'INSPECT_ARTIFACT_IN_REGISTRY',
  REMOVE_ARTIFACT: 'REMOVE_ARTIFACT',
  UPDATE_SANDBOX_NETWORK_SETTINGS: 'UPDATE_SANDBOX_NETWORK_SETTINGS',
} as const

export type JobType = (typeof JobType)[keyof typeof JobType]
