/* tslint:disable */
/* eslint-disable */
/**
 * BoxLite
 * BoxLite AI platform API Docs
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@boxlite.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { Box } from './box'

/**
 *
 * @export
 * @interface ListBoxesResponse
 */
export interface ListBoxesResponse {
  /**
   * @type {Array<Box>}
   * @memberof ListBoxesResponse
   */
  boxes: Array<Box>
  /**
   * Token for the next page when pagination is available
   * @type {string}
   * @memberof ListBoxesResponse
   */
  nextPageToken?: string
}
