/* tslint:disable */
/* eslint-disable */
/**
 * BoxLite
 * BoxLite AI platform API Docs
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@boxlite.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

// May contain unused imports in some cases
// @ts-ignore
import type { SavedImageDto } from './saved-image-dto';

/**
 *
 * @export
 * @interface PaginatedSavedImages
 */
export interface PaginatedSavedImages {
    /**
     *
     * @type {Array<SavedImageDto>}
     * @memberof PaginatedSavedImages
     */
    'items': Array<SavedImageDto>;
    /**
     *
     * @type {number}
     * @memberof PaginatedSavedImages
     */
    'total': number;
    /**
     *
     * @type {number}
     * @memberof PaginatedSavedImages
     */
    'page': number;
    /**
     *
     * @type {number}
     * @memberof PaginatedSavedImages
     */
    'totalPages': number;
}
