/* tslint:disable */
/* eslint-disable */
/**
 * BoxLite
 * BoxLite AI platform API Docs
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@boxlite.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * The state of the sandbox
 * @export
 * @enum {string}
 */

export const SandboxState = {
  CREATING: 'creating',
  RESTORING: 'restoring',
  DESTROYED: 'destroyed',
  DESTROYING: 'destroying',
  STARTED: 'started',
  STOPPED: 'stopped',
  STARTING: 'starting',
  STOPPING: 'stopping',
  ERROR: 'error',
  BUILD_FAILED: 'build_failed',
  PENDING_BUILD: 'pending_build',
  BUILDING_ARTIFACT: 'building_artifact',
  UNKNOWN: 'unknown',
  PULLING_ARTIFACT: 'pulling_artifact',
  ARCHIVED: 'archived',
  ARCHIVING: 'archiving',
  RESIZING: 'resizing',
} as const

export type SandboxState = (typeof SandboxState)[keyof typeof SandboxState]
