/* tslint:disable */
/* eslint-disable */
/**
 * BoxLite
 * BoxLite AI platform API Docs
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@boxlite.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { SavedImageDefaultResourcesDto } from './saved-image-default-resources-dto';
// May contain unused imports in some cases
// @ts-ignore
import type { SavedImageState } from './saved-image-state';
// May contain unused imports in some cases
// @ts-ignore
import type { BuildInfo } from './build-info';

/**
 *
 * @export
 * @interface SavedImageDto
 */
export interface SavedImageDto {
    /**
     *
     * @type {string}
     * @memberof SavedImageDto
     */
    'id': string;
    /**
     *
     * @type {string}
     * @memberof SavedImageDto
     */
    'organizationId'?: string;
    /**
     *
     * @type {boolean}
     * @memberof SavedImageDto
     */
    'general': boolean;
    /**
     *
     * @type {string}
     * @memberof SavedImageDto
     */
    'name': string;
    /**
     *
     * @type {string}
     * @memberof SavedImageDto
     */
    'displayName': string;
    /**
     *
     * @type {string}
     * @memberof SavedImageDto
     */
    'description'?: string;
    /**
     *
     * @type {string}
     * @memberof SavedImageDto
     */
    'artifactRef'?: string;
    /**
     *
     * @type {SavedImageState}
     * @memberof SavedImageDto
     */
    'state': SavedImageState;
    /**
     *
     * @type {string}
     * @memberof SavedImageDto
     */
    'errorReason'?: string;
    /**
     *
     * @type {SavedImageDefaultResourcesDto}
     * @memberof SavedImageDto
     */
    'defaultResources': SavedImageDefaultResourcesDto;
    /**
     *
     * @type {Date}
     * @memberof SavedImageDto
     */
    'createdAt': Date;
    /**
     *
     * @type {Date}
     * @memberof SavedImageDto
     */
    'updatedAt': Date;
    /**
     *
     * @type {Date}
     * @memberof SavedImageDto
     */
    'lastUsedAt'?: Date;
    /**
     * Build information for this savedImage
     * @type {BuildInfo}
     * @memberof SavedImageDto
     */
    'buildInfo'?: BuildInfo;
    /**
     * The initial runner ID of the savedImage
     * @type {string}
     * @memberof SavedImageDto
     */
    'initialRunnerId'?: string;
    /**
     * IDs of regions where the saved image is available to this organization
     * @type {Array<string>}
     * @memberof SavedImageDto
     */
    'regionIds'?: Array<string>;
}
