/* tslint:disable */
/* eslint-disable */
/**
 * BoxLite
 * BoxLite AI platform API Docs
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@boxlite.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 *
 * @export
 * @interface SavedImageDefaultResourcesDto
 */
export interface SavedImageDefaultResourcesDto {
    /**
     *
     * @type {number}
     * @memberof SavedImageDefaultResourcesDto
     */
    'cpu': number;
    /**
     *
     * @type {number}
     * @memberof SavedImageDefaultResourcesDto
     */
    'gpu': number;
    /**
     *
     * @type {number}
     * @memberof SavedImageDefaultResourcesDto
     */
    'memory': number;
    /**
     *
     * @type {number}
     * @memberof SavedImageDefaultResourcesDto
     */
    'disk': number;
}
