/* tslint:disable */
/* eslint-disable */
/**
 * BoxLite
 * BoxLite AI platform API Docs
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@boxlite.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface UpdateOrganizationQuota
 */
export interface UpdateOrganizationQuota {
  /**
   *
   * @type {number}
   * @memberof UpdateOrganizationQuota
   */
  maxCpuPerSandbox: number | null
  /**
   *
   * @type {number}
   * @memberof UpdateOrganizationQuota
   */
  maxMemoryPerSandbox: number | null
  /**
   *
   * @type {number}
   * @memberof UpdateOrganizationQuota
   */
  maxDiskPerSandbox: number | null
  /**
   *
   * @type {number}
   * @memberof UpdateOrganizationQuota
   */
  templateQuota: number | null
  /**
   *
   * @type {number}
   * @memberof UpdateOrganizationQuota
   */
  maxTemplateSize: number | null
  /**
   *
   * @type {number}
   * @memberof UpdateOrganizationQuota
   */
  volumeQuota: number | null
  /**
   *
   * @type {number}
   * @memberof UpdateOrganizationQuota
   */
  authenticatedRateLimit: number | null
  /**
   *
   * @type {number}
   * @memberof UpdateOrganizationQuota
   */
  sandboxCreateRateLimit: number | null
  /**
   *
   * @type {number}
   * @memberof UpdateOrganizationQuota
   */
  sandboxLifecycleRateLimit: number | null
  /**
   *
   * @type {number}
   * @memberof UpdateOrganizationQuota
   */
  authenticatedRateLimitTtlSeconds: number | null
  /**
   *
   * @type {number}
   * @memberof UpdateOrganizationQuota
   */
  sandboxCreateRateLimitTtlSeconds: number | null
  /**
   *
   * @type {number}
   * @memberof UpdateOrganizationQuota
   */
  sandboxLifecycleRateLimitTtlSeconds: number | null
  /**
   * Time in minutes before an unused template is deactivated
   * @type {number}
   * @memberof UpdateOrganizationQuota
   */
  templateDeactivationTimeoutMinutes: number | null
}
