/* tslint:disable */
/* eslint-disable */
/**
 * BoxLite
 * BoxLite AI platform API Docs
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@boxlite.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface UpdateRegion
 */
export interface UpdateRegion {
  /**
   * Proxy URL for the region
   * @type {string}
   * @memberof UpdateRegion
   */
  proxyUrl?: string | null
  /**
   * SSH Gateway URL for the region
   * @type {string}
   * @memberof UpdateRegion
   */
  sshGatewayUrl?: string | null
  /**
   * Artifact Registry URL for the region
   * @type {string}
   * @memberof UpdateRegion
   */
  artifactRegistryUrl?: string | null
}
