/* tslint:disable */
/* eslint-disable */
/**
 * BoxLite
 * BoxLite AI platform API Docs
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@boxlite.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * The type of event being sent
 * @export
 * @enum {string}
 */

export const WebhookEvent = {
    SANDBOX_CREATED: 'sandbox.created',
    SANDBOX_STATE_UPDATED: 'sandbox.state.updated',
    SAVED_IMAGE_CREATED: 'savedImage.created',
    SAVED_IMAGE_STATE_UPDATED: 'savedImage.state.updated',
    SAVED_IMAGE_REMOVED: 'savedImage.removed',
    VOLUME_CREATED: 'volume.created',
    VOLUME_STATE_UPDATED: 'volume.state.updated'
} as const;

export type WebhookEvent = typeof WebhookEvent[keyof typeof WebhookEvent];
