/* tslint:disable */
/* eslint-disable */
/**
 * BoxLite Runner API
 * BoxLite Runner API
 *
 * The version of the OpenAPI document: v0.0.0-dev
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { Configuration } from '../configuration'
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios'
import globalAxios from 'axios'
// Some imports not used depending on template conditions
// @ts-ignore
import {
  DUMMY_BASE_URL,
  assertParamExists,
  setApiKeyToObject,
  setBasicAuthToObject,
  setBearerAuthToObject,
  setOAuthToObject,
  setSearchParams,
  serializeDataIfNeeded,
  toPathString,
  createRequestFunction,
} from '../common'
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, type RequestArgs, BaseAPI, RequiredError, operationServerMap } from '../base'
// @ts-ignore
import type { ArtifactDigestResponse } from '../models'
// @ts-ignore
import type { ArtifactExistsResponse } from '../models'
// @ts-ignore
import type { ArtifactInfoResponse } from '../models'
// @ts-ignore
import type { BuildArtifactRequestDTO } from '../models'
// @ts-ignore
import type { ErrorResponse } from '../models'
// @ts-ignore
import type { InspectArtifactInRegistryRequest } from '../models'
// @ts-ignore
import type { PullArtifactRequestDTO } from '../models'
// @ts-ignore
import type { TagImageRequestDTO } from '../models'
/**
 * ArtifactsApi - axios parameter creator
 * @export
 */
export const ArtifactsApiAxiosParamCreator = function (configuration?: Configuration) {
  return {
    /**
     * Check if a specified artifact exists locally
     * @summary Check if an artifact exists
     * @param {string} artifactRef Artifact ref
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    artifactExists: async (artifactRef: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
      // verify required parameter 'artifactRef' is not null or undefined
      assertParamExists('artifactExists', 'artifactRef', artifactRef)
      const localVarPath = `/artifacts/exists`
      // use dummy base URL string because the URL constructor only accepts absolute URLs.
      const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL)
      let baseOptions
      if (configuration) {
        baseOptions = configuration.baseOptions
      }

      const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options }
      const localVarHeaderParameter = {} as any
      const localVarQueryParameter = {} as any

      // authentication Bearer required
      await setApiKeyToObject(localVarHeaderParameter, 'Authorization', configuration)

      if (artifactRef !== undefined) {
        localVarQueryParameter['artifactRef'] = artifactRef
      }

      setSearchParams(localVarUrlObj, localVarQueryParameter)
      let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {}
      localVarRequestOptions.headers = { ...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers }

      return {
        url: toPathString(localVarUrlObj),
        options: localVarRequestOptions,
      }
    },
    /**
     * Build an artifact from a Dockerfile and context hashes. The operation runs asynchronously and returns 202 immediately.
     * @summary Build an artifact
     * @param {BuildArtifactRequestDTO} request Build artifact request
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    buildArtifact: async (
      request: BuildArtifactRequestDTO,
      options: RawAxiosRequestConfig = {},
    ): Promise<RequestArgs> => {
      // verify required parameter 'request' is not null or undefined
      assertParamExists('buildArtifact', 'request', request)
      const localVarPath = `/artifacts/build`
      // use dummy base URL string because the URL constructor only accepts absolute URLs.
      const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL)
      let baseOptions
      if (configuration) {
        baseOptions = configuration.baseOptions
      }

      const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options }
      const localVarHeaderParameter = {} as any
      const localVarQueryParameter = {} as any

      // authentication Bearer required
      await setApiKeyToObject(localVarHeaderParameter, 'Authorization', configuration)

      localVarHeaderParameter['Content-Type'] = 'application/json'

      setSearchParams(localVarUrlObj, localVarQueryParameter)
      let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {}
      localVarRequestOptions.headers = { ...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers }
      localVarRequestOptions.data = serializeDataIfNeeded(request, localVarRequestOptions, configuration)

      return {
        url: toPathString(localVarUrlObj),
        options: localVarRequestOptions,
      }
    },
    /**
     * Get information about a specified artifact including size and entrypoint. Returns 422 if the last pull/build operation failed, with the error reason in the message.
     * @summary Get artifact information
     * @param {string} artifactRef Artifact ref
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    getArtifactInfo: async (artifactRef: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
      // verify required parameter 'artifactRef' is not null or undefined
      assertParamExists('getArtifactInfo', 'artifactRef', artifactRef)
      const localVarPath = `/artifacts/info`
      // use dummy base URL string because the URL constructor only accepts absolute URLs.
      const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL)
      let baseOptions
      if (configuration) {
        baseOptions = configuration.baseOptions
      }

      const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options }
      const localVarHeaderParameter = {} as any
      const localVarQueryParameter = {} as any

      // authentication Bearer required
      await setApiKeyToObject(localVarHeaderParameter, 'Authorization', configuration)

      if (artifactRef !== undefined) {
        localVarQueryParameter['artifactRef'] = artifactRef
      }

      setSearchParams(localVarUrlObj, localVarQueryParameter)
      let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {}
      localVarRequestOptions.headers = { ...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers }

      return {
        url: toPathString(localVarUrlObj),
        options: localVarRequestOptions,
      }
    },
    /**
     * Stream build logs
     * @summary Get build logs
     * @param {string} artifactRef Runtime artifact ref
     * @param {boolean} [follow] Whether to follow the log output
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    getBuildLogs: async (
      artifactRef: string,
      follow?: boolean,
      options: RawAxiosRequestConfig = {},
    ): Promise<RequestArgs> => {
      // verify required parameter 'artifactRef' is not null or undefined
      assertParamExists('getBuildLogs', 'artifactRef', artifactRef)
      const localVarPath = `/artifacts/logs`
      // use dummy base URL string because the URL constructor only accepts absolute URLs.
      const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL)
      let baseOptions
      if (configuration) {
        baseOptions = configuration.baseOptions
      }

      const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options }
      const localVarHeaderParameter = {} as any
      const localVarQueryParameter = {} as any

      // authentication Bearer required
      await setApiKeyToObject(localVarHeaderParameter, 'Authorization', configuration)

      if (artifactRef !== undefined) {
        localVarQueryParameter['artifactRef'] = artifactRef
      }

      if (follow !== undefined) {
        localVarQueryParameter['follow'] = follow
      }

      setSearchParams(localVarUrlObj, localVarQueryParameter)
      let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {}
      localVarRequestOptions.headers = { ...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers }

      return {
        url: toPathString(localVarUrlObj),
        options: localVarRequestOptions,
      }
    },
    /**
     * Inspect a specified artifact in a registry
     * @summary Inspect an artifact in a registry
     * @param {InspectArtifactInRegistryRequest} request Inspect artifact in registry request
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    inspectArtifactInRegistry: async (
      request: InspectArtifactInRegistryRequest,
      options: RawAxiosRequestConfig = {},
    ): Promise<RequestArgs> => {
      // verify required parameter 'request' is not null or undefined
      assertParamExists('inspectArtifactInRegistry', 'request', request)
      const localVarPath = `/artifacts/inspect`
      // use dummy base URL string because the URL constructor only accepts absolute URLs.
      const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL)
      let baseOptions
      if (configuration) {
        baseOptions = configuration.baseOptions
      }

      const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options }
      const localVarHeaderParameter = {} as any
      const localVarQueryParameter = {} as any

      // authentication Bearer required
      await setApiKeyToObject(localVarHeaderParameter, 'Authorization', configuration)

      localVarHeaderParameter['Content-Type'] = 'application/json'

      setSearchParams(localVarUrlObj, localVarQueryParameter)
      let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {}
      localVarRequestOptions.headers = { ...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers }
      localVarRequestOptions.data = serializeDataIfNeeded(request, localVarRequestOptions, configuration)

      return {
        url: toPathString(localVarUrlObj),
        options: localVarRequestOptions,
      }
    },
    /**
     * Pull an artifact from a registry and optionally push to another registry. The operation runs asynchronously and returns 202 immediately.
     * @summary Pull an artifact
     * @param {PullArtifactRequestDTO} request Pull artifact
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    pullArtifact: async (
      request: PullArtifactRequestDTO,
      options: RawAxiosRequestConfig = {},
    ): Promise<RequestArgs> => {
      // verify required parameter 'request' is not null or undefined
      assertParamExists('pullArtifact', 'request', request)
      const localVarPath = `/artifacts/pull`
      // use dummy base URL string because the URL constructor only accepts absolute URLs.
      const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL)
      let baseOptions
      if (configuration) {
        baseOptions = configuration.baseOptions
      }

      const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options }
      const localVarHeaderParameter = {} as any
      const localVarQueryParameter = {} as any

      // authentication Bearer required
      await setApiKeyToObject(localVarHeaderParameter, 'Authorization', configuration)

      localVarHeaderParameter['Content-Type'] = 'application/json'

      setSearchParams(localVarUrlObj, localVarQueryParameter)
      let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {}
      localVarRequestOptions.headers = { ...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers }
      localVarRequestOptions.data = serializeDataIfNeeded(request, localVarRequestOptions, configuration)

      return {
        url: toPathString(localVarUrlObj),
        options: localVarRequestOptions,
      }
    },
    /**
     * Remove a specified artifact from the local system
     * @summary Remove an artifact
     * @param {string} artifactRef Artifact ref
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    removeArtifact: async (artifactRef: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
      // verify required parameter 'artifactRef' is not null or undefined
      assertParamExists('removeArtifact', 'artifactRef', artifactRef)
      const localVarPath = `/artifacts/remove`
      // use dummy base URL string because the URL constructor only accepts absolute URLs.
      const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL)
      let baseOptions
      if (configuration) {
        baseOptions = configuration.baseOptions
      }

      const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options }
      const localVarHeaderParameter = {} as any
      const localVarQueryParameter = {} as any

      // authentication Bearer required
      await setApiKeyToObject(localVarHeaderParameter, 'Authorization', configuration)

      if (artifactRef !== undefined) {
        localVarQueryParameter['artifactRef'] = artifactRef
      }

      setSearchParams(localVarUrlObj, localVarQueryParameter)
      let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {}
      localVarRequestOptions.headers = { ...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers }

      return {
        url: toPathString(localVarUrlObj),
        options: localVarRequestOptions,
      }
    },
    /**
     * Tag an existing local image with a new target reference
     * @summary Tag an image
     * @param {TagImageRequestDTO} request Tag image request
     * @param {*} [options] Override http request option.
     * @deprecated
     * @throws {RequiredError}
     */
    tagImage: async (request: TagImageRequestDTO, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
      // verify required parameter 'request' is not null or undefined
      assertParamExists('tagImage', 'request', request)
      const localVarPath = `/artifacts/tag`
      // use dummy base URL string because the URL constructor only accepts absolute URLs.
      const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL)
      let baseOptions
      if (configuration) {
        baseOptions = configuration.baseOptions
      }

      const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options }
      const localVarHeaderParameter = {} as any
      const localVarQueryParameter = {} as any

      // authentication Bearer required
      await setApiKeyToObject(localVarHeaderParameter, 'Authorization', configuration)

      localVarHeaderParameter['Content-Type'] = 'application/json'

      setSearchParams(localVarUrlObj, localVarQueryParameter)
      let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {}
      localVarRequestOptions.headers = { ...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers }
      localVarRequestOptions.data = serializeDataIfNeeded(request, localVarRequestOptions, configuration)

      return {
        url: toPathString(localVarUrlObj),
        options: localVarRequestOptions,
      }
    },
  }
}

/**
 * ArtifactsApi - functional programming interface
 * @export
 */
export const ArtifactsApiFp = function (configuration?: Configuration) {
  const localVarAxiosParamCreator = ArtifactsApiAxiosParamCreator(configuration)
  return {
    /**
     * Check if a specified artifact exists locally
     * @summary Check if an artifact exists
     * @param {string} artifactRef Artifact ref
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    async artifactExists(
      artifactRef: string,
      options?: RawAxiosRequestConfig,
    ): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ArtifactExistsResponse>> {
      const localVarAxiosArgs = await localVarAxiosParamCreator.artifactExists(artifactRef, options)
      const localVarOperationServerIndex = configuration?.serverIndex ?? 0
      const localVarOperationServerBasePath =
        operationServerMap['ArtifactsApi.artifactExists']?.[localVarOperationServerIndex]?.url
      return (axios, basePath) =>
        createRequestFunction(
          localVarAxiosArgs,
          globalAxios,
          BASE_PATH,
          configuration,
        )(axios, localVarOperationServerBasePath || basePath)
    },
    /**
     * Build an artifact from a Dockerfile and context hashes. The operation runs asynchronously and returns 202 immediately.
     * @summary Build an artifact
     * @param {BuildArtifactRequestDTO} request Build artifact request
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    async buildArtifact(
      request: BuildArtifactRequestDTO,
      options?: RawAxiosRequestConfig,
    ): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<string>> {
      const localVarAxiosArgs = await localVarAxiosParamCreator.buildArtifact(request, options)
      const localVarOperationServerIndex = configuration?.serverIndex ?? 0
      const localVarOperationServerBasePath =
        operationServerMap['ArtifactsApi.buildArtifact']?.[localVarOperationServerIndex]?.url
      return (axios, basePath) =>
        createRequestFunction(
          localVarAxiosArgs,
          globalAxios,
          BASE_PATH,
          configuration,
        )(axios, localVarOperationServerBasePath || basePath)
    },
    /**
     * Get information about a specified artifact including size and entrypoint. Returns 422 if the last pull/build operation failed, with the error reason in the message.
     * @summary Get artifact information
     * @param {string} artifactRef Artifact ref
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    async getArtifactInfo(
      artifactRef: string,
      options?: RawAxiosRequestConfig,
    ): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ArtifactInfoResponse>> {
      const localVarAxiosArgs = await localVarAxiosParamCreator.getArtifactInfo(artifactRef, options)
      const localVarOperationServerIndex = configuration?.serverIndex ?? 0
      const localVarOperationServerBasePath =
        operationServerMap['ArtifactsApi.getArtifactInfo']?.[localVarOperationServerIndex]?.url
      return (axios, basePath) =>
        createRequestFunction(
          localVarAxiosArgs,
          globalAxios,
          BASE_PATH,
          configuration,
        )(axios, localVarOperationServerBasePath || basePath)
    },
    /**
     * Stream build logs
     * @summary Get build logs
     * @param {string} artifactRef Runtime artifact ref
     * @param {boolean} [follow] Whether to follow the log output
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    async getBuildLogs(
      artifactRef: string,
      follow?: boolean,
      options?: RawAxiosRequestConfig,
    ): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<string>> {
      const localVarAxiosArgs = await localVarAxiosParamCreator.getBuildLogs(artifactRef, follow, options)
      const localVarOperationServerIndex = configuration?.serverIndex ?? 0
      const localVarOperationServerBasePath =
        operationServerMap['ArtifactsApi.getBuildLogs']?.[localVarOperationServerIndex]?.url
      return (axios, basePath) =>
        createRequestFunction(
          localVarAxiosArgs,
          globalAxios,
          BASE_PATH,
          configuration,
        )(axios, localVarOperationServerBasePath || basePath)
    },
    /**
     * Inspect a specified artifact in a registry
     * @summary Inspect an artifact in a registry
     * @param {InspectArtifactInRegistryRequest} request Inspect artifact in registry request
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    async inspectArtifactInRegistry(
      request: InspectArtifactInRegistryRequest,
      options?: RawAxiosRequestConfig,
    ): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ArtifactDigestResponse>> {
      const localVarAxiosArgs = await localVarAxiosParamCreator.inspectArtifactInRegistry(request, options)
      const localVarOperationServerIndex = configuration?.serverIndex ?? 0
      const localVarOperationServerBasePath =
        operationServerMap['ArtifactsApi.inspectArtifactInRegistry']?.[localVarOperationServerIndex]?.url
      return (axios, basePath) =>
        createRequestFunction(
          localVarAxiosArgs,
          globalAxios,
          BASE_PATH,
          configuration,
        )(axios, localVarOperationServerBasePath || basePath)
    },
    /**
     * Pull an artifact from a registry and optionally push to another registry. The operation runs asynchronously and returns 202 immediately.
     * @summary Pull an artifact
     * @param {PullArtifactRequestDTO} request Pull artifact
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    async pullArtifact(
      request: PullArtifactRequestDTO,
      options?: RawAxiosRequestConfig,
    ): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<string>> {
      const localVarAxiosArgs = await localVarAxiosParamCreator.pullArtifact(request, options)
      const localVarOperationServerIndex = configuration?.serverIndex ?? 0
      const localVarOperationServerBasePath =
        operationServerMap['ArtifactsApi.pullArtifact']?.[localVarOperationServerIndex]?.url
      return (axios, basePath) =>
        createRequestFunction(
          localVarAxiosArgs,
          globalAxios,
          BASE_PATH,
          configuration,
        )(axios, localVarOperationServerBasePath || basePath)
    },
    /**
     * Remove a specified artifact from the local system
     * @summary Remove an artifact
     * @param {string} artifactRef Artifact ref
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    async removeArtifact(
      artifactRef: string,
      options?: RawAxiosRequestConfig,
    ): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<string>> {
      const localVarAxiosArgs = await localVarAxiosParamCreator.removeArtifact(artifactRef, options)
      const localVarOperationServerIndex = configuration?.serverIndex ?? 0
      const localVarOperationServerBasePath =
        operationServerMap['ArtifactsApi.removeArtifact']?.[localVarOperationServerIndex]?.url
      return (axios, basePath) =>
        createRequestFunction(
          localVarAxiosArgs,
          globalAxios,
          BASE_PATH,
          configuration,
        )(axios, localVarOperationServerBasePath || basePath)
    },
    /**
     * Tag an existing local image with a new target reference
     * @summary Tag an image
     * @param {TagImageRequestDTO} request Tag image request
     * @param {*} [options] Override http request option.
     * @deprecated
     * @throws {RequiredError}
     */
    async tagImage(
      request: TagImageRequestDTO,
      options?: RawAxiosRequestConfig,
    ): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<string>> {
      const localVarAxiosArgs = await localVarAxiosParamCreator.tagImage(request, options)
      const localVarOperationServerIndex = configuration?.serverIndex ?? 0
      const localVarOperationServerBasePath =
        operationServerMap['ArtifactsApi.tagImage']?.[localVarOperationServerIndex]?.url
      return (axios, basePath) =>
        createRequestFunction(
          localVarAxiosArgs,
          globalAxios,
          BASE_PATH,
          configuration,
        )(axios, localVarOperationServerBasePath || basePath)
    },
  }
}

/**
 * ArtifactsApi - factory interface
 * @export
 */
export const ArtifactsApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
  const localVarFp = ArtifactsApiFp(configuration)
  return {
    /**
     * Check if a specified artifact exists locally
     * @summary Check if an artifact exists
     * @param {string} artifactRef Artifact ref
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    artifactExists(artifactRef: string, options?: RawAxiosRequestConfig): AxiosPromise<ArtifactExistsResponse> {
      return localVarFp.artifactExists(artifactRef, options).then((request) => request(axios, basePath))
    },
    /**
     * Build an artifact from a Dockerfile and context hashes. The operation runs asynchronously and returns 202 immediately.
     * @summary Build an artifact
     * @param {BuildArtifactRequestDTO} request Build artifact request
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    buildArtifact(request: BuildArtifactRequestDTO, options?: RawAxiosRequestConfig): AxiosPromise<string> {
      return localVarFp.buildArtifact(request, options).then((request) => request(axios, basePath))
    },
    /**
     * Get information about a specified artifact including size and entrypoint. Returns 422 if the last pull/build operation failed, with the error reason in the message.
     * @summary Get artifact information
     * @param {string} artifactRef Artifact ref
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    getArtifactInfo(artifactRef: string, options?: RawAxiosRequestConfig): AxiosPromise<ArtifactInfoResponse> {
      return localVarFp.getArtifactInfo(artifactRef, options).then((request) => request(axios, basePath))
    },
    /**
     * Stream build logs
     * @summary Get build logs
     * @param {string} artifactRef Runtime artifact ref
     * @param {boolean} [follow] Whether to follow the log output
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    getBuildLogs(artifactRef: string, follow?: boolean, options?: RawAxiosRequestConfig): AxiosPromise<string> {
      return localVarFp.getBuildLogs(artifactRef, follow, options).then((request) => request(axios, basePath))
    },
    /**
     * Inspect a specified artifact in a registry
     * @summary Inspect an artifact in a registry
     * @param {InspectArtifactInRegistryRequest} request Inspect artifact in registry request
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    inspectArtifactInRegistry(
      request: InspectArtifactInRegistryRequest,
      options?: RawAxiosRequestConfig,
    ): AxiosPromise<ArtifactDigestResponse> {
      return localVarFp.inspectArtifactInRegistry(request, options).then((request) => request(axios, basePath))
    },
    /**
     * Pull an artifact from a registry and optionally push to another registry. The operation runs asynchronously and returns 202 immediately.
     * @summary Pull an artifact
     * @param {PullArtifactRequestDTO} request Pull artifact
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    pullArtifact(request: PullArtifactRequestDTO, options?: RawAxiosRequestConfig): AxiosPromise<string> {
      return localVarFp.pullArtifact(request, options).then((request) => request(axios, basePath))
    },
    /**
     * Remove a specified artifact from the local system
     * @summary Remove an artifact
     * @param {string} artifactRef Artifact ref
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    removeArtifact(artifactRef: string, options?: RawAxiosRequestConfig): AxiosPromise<string> {
      return localVarFp.removeArtifact(artifactRef, options).then((request) => request(axios, basePath))
    },
    /**
     * Tag an existing local image with a new target reference
     * @summary Tag an image
     * @param {TagImageRequestDTO} request Tag image request
     * @param {*} [options] Override http request option.
     * @deprecated
     * @throws {RequiredError}
     */
    tagImage(request: TagImageRequestDTO, options?: RawAxiosRequestConfig): AxiosPromise<string> {
      return localVarFp.tagImage(request, options).then((request) => request(axios, basePath))
    },
  }
}

/**
 * ArtifactsApi - object-oriented interface
 * @export
 * @class ArtifactsApi
 * @extends {BaseAPI}
 */
export class ArtifactsApi extends BaseAPI {
  /**
   * Check if a specified artifact exists locally
   * @summary Check if an artifact exists
   * @param {string} artifactRef Artifact ref
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   * @memberof ArtifactsApi
   */
  public artifactExists(artifactRef: string, options?: RawAxiosRequestConfig) {
    return ArtifactsApiFp(this.configuration)
      .artifactExists(artifactRef, options)
      .then((request) => request(this.axios, this.basePath))
  }

  /**
   * Build an artifact from a Dockerfile and context hashes. The operation runs asynchronously and returns 202 immediately.
   * @summary Build an artifact
   * @param {BuildArtifactRequestDTO} request Build artifact request
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   * @memberof ArtifactsApi
   */
  public buildArtifact(request: BuildArtifactRequestDTO, options?: RawAxiosRequestConfig) {
    return ArtifactsApiFp(this.configuration)
      .buildArtifact(request, options)
      .then((request) => request(this.axios, this.basePath))
  }

  /**
   * Get information about a specified artifact including size and entrypoint. Returns 422 if the last pull/build operation failed, with the error reason in the message.
   * @summary Get artifact information
   * @param {string} artifactRef Artifact ref
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   * @memberof ArtifactsApi
   */
  public getArtifactInfo(artifactRef: string, options?: RawAxiosRequestConfig) {
    return ArtifactsApiFp(this.configuration)
      .getArtifactInfo(artifactRef, options)
      .then((request) => request(this.axios, this.basePath))
  }

  /**
   * Stream build logs
   * @summary Get build logs
   * @param {string} artifactRef Runtime artifact ref
   * @param {boolean} [follow] Whether to follow the log output
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   * @memberof ArtifactsApi
   */
  public getBuildLogs(artifactRef: string, follow?: boolean, options?: RawAxiosRequestConfig) {
    return ArtifactsApiFp(this.configuration)
      .getBuildLogs(artifactRef, follow, options)
      .then((request) => request(this.axios, this.basePath))
  }

  /**
   * Inspect a specified artifact in a registry
   * @summary Inspect an artifact in a registry
   * @param {InspectArtifactInRegistryRequest} request Inspect artifact in registry request
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   * @memberof ArtifactsApi
   */
  public inspectArtifactInRegistry(request: InspectArtifactInRegistryRequest, options?: RawAxiosRequestConfig) {
    return ArtifactsApiFp(this.configuration)
      .inspectArtifactInRegistry(request, options)
      .then((request) => request(this.axios, this.basePath))
  }

  /**
   * Pull an artifact from a registry and optionally push to another registry. The operation runs asynchronously and returns 202 immediately.
   * @summary Pull an artifact
   * @param {PullArtifactRequestDTO} request Pull artifact
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   * @memberof ArtifactsApi
   */
  public pullArtifact(request: PullArtifactRequestDTO, options?: RawAxiosRequestConfig) {
    return ArtifactsApiFp(this.configuration)
      .pullArtifact(request, options)
      .then((request) => request(this.axios, this.basePath))
  }

  /**
   * Remove a specified artifact from the local system
   * @summary Remove an artifact
   * @param {string} artifactRef Artifact ref
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   * @memberof ArtifactsApi
   */
  public removeArtifact(artifactRef: string, options?: RawAxiosRequestConfig) {
    return ArtifactsApiFp(this.configuration)
      .removeArtifact(artifactRef, options)
      .then((request) => request(this.axios, this.basePath))
  }

  /**
   * Tag an existing local image with a new target reference
   * @summary Tag an image
   * @param {TagImageRequestDTO} request Tag image request
   * @param {*} [options] Override http request option.
   * @deprecated
   * @throws {RequiredError}
   * @memberof ArtifactsApi
   */
  public tagImage(request: TagImageRequestDTO, options?: RawAxiosRequestConfig) {
    return ArtifactsApiFp(this.configuration)
      .tagImage(request, options)
      .then((request) => request(this.axios, this.basePath))
  }
}
