/*
BoxLite

BoxLite AI platform API Docs

API version: 1.0
Contact: support@boxlite.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package apiclient

import "time"

// SavedImageDto struct for SavedImageDto
type SavedImageDto struct {
	Id                   string     `json:"id"`
	OrganizationId       *string    `json:"organizationId,omitempty"`
	General              bool       `json:"general"`
	Name                 string     `json:"name"`
	DisplayName          string     `json:"displayName"`
	Description          *string    `json:"description,omitempty"`
	ArtifactRef          *string    `json:"artifactRef,omitempty"`
	State                string     `json:"state"`
	ErrorReason          *string    `json:"errorReason,omitempty"`
	CreatedAt            time.Time  `json:"createdAt"`
	UpdatedAt            time.Time  `json:"updatedAt"`
	LastUsedAt           *time.Time `json:"lastUsedAt,omitempty"`
	BuildInfo            *BuildInfo `json:"buildInfo,omitempty"`
	InitialRunnerId      *string    `json:"initialRunnerId,omitempty"`
	RegionIds            []string   `json:"regionIds,omitempty"`
	AdditionalProperties map[string]interface{}
}
