/*
BoxLite

BoxLite AI platform API Docs

API version: 1.0
Contact: support@boxlite.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package apiclient

import (
	"encoding/json"
	"fmt"
)

// checks if the Box type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &Box{}

// Box struct for Box
type Box struct {
	// The public 12-character Box ID shown to users and SDK clients
	BoxId string `json:"box_id"`
	// User-provided box name
	Name *string `json:"name,omitempty"`
	// Box runtime status
	Status string `json:"status"`
	// Creation timestamp
	CreatedAt string `json:"created_at"`
	// Last update timestamp
	UpdatedAt string `json:"updated_at"`
	// Runtime process ID when available
	Pid *float32 `json:"pid,omitempty"`
	// Approved image/template used for the box
	Image string `json:"image"`
	// Allocated CPU count
	Cpus float32 `json:"cpus"`
	// Allocated memory in MiB
	MemoryMib float32 `json:"memory_mib"`
	// Labels attached to the box
	Labels               map[string]string `json:"labels"`
	AdditionalProperties map[string]interface{}
}

type _Box Box

// NewBox instantiates a new Box object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewBox(boxId string, status string, createdAt string, updatedAt string, image string, cpus float32, memoryMib float32, labels map[string]string) *Box {
	this := Box{}
	this.BoxId = boxId
	this.Status = status
	this.CreatedAt = createdAt
	this.UpdatedAt = updatedAt
	this.Image = image
	this.Cpus = cpus
	this.MemoryMib = memoryMib
	this.Labels = labels
	return &this
}

// NewBoxWithDefaults instantiates a new Box object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewBoxWithDefaults() *Box {
	this := Box{}
	return &this
}

// GetBoxId returns the BoxId field value
func (o *Box) GetBoxId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.BoxId
}

// GetBoxIdOk returns a tuple with the BoxId field value
// and a boolean to check if the value has been set.
func (o *Box) GetBoxIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.BoxId, true
}

// SetBoxId sets field value
func (o *Box) SetBoxId(v string) {
	o.BoxId = v
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *Box) GetName() string {
	if o == nil || IsNil(o.Name) {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Box) GetNameOk() (*string, bool) {
	if o == nil || IsNil(o.Name) {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *Box) HasName() bool {
	if o != nil && !IsNil(o.Name) {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *Box) SetName(v string) {
	o.Name = &v
}

// GetStatus returns the Status field value
func (o *Box) GetStatus() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Status
}

// GetStatusOk returns a tuple with the Status field value
// and a boolean to check if the value has been set.
func (o *Box) GetStatusOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Status, true
}

// SetStatus sets field value
func (o *Box) SetStatus(v string) {
	o.Status = v
}

// GetCreatedAt returns the CreatedAt field value
func (o *Box) GetCreatedAt() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.CreatedAt
}

// GetCreatedAtOk returns a tuple with the CreatedAt field value
// and a boolean to check if the value has been set.
func (o *Box) GetCreatedAtOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CreatedAt, true
}

// SetCreatedAt sets field value
func (o *Box) SetCreatedAt(v string) {
	o.CreatedAt = v
}

// GetUpdatedAt returns the UpdatedAt field value
func (o *Box) GetUpdatedAt() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.UpdatedAt
}

// GetUpdatedAtOk returns a tuple with the UpdatedAt field value
// and a boolean to check if the value has been set.
func (o *Box) GetUpdatedAtOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.UpdatedAt, true
}

// SetUpdatedAt sets field value
func (o *Box) SetUpdatedAt(v string) {
	o.UpdatedAt = v
}

// GetPid returns the Pid field value if set, zero value otherwise.
func (o *Box) GetPid() float32 {
	if o == nil || IsNil(o.Pid) {
		var ret float32
		return ret
	}
	return *o.Pid
}

// GetPidOk returns a tuple with the Pid field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Box) GetPidOk() (*float32, bool) {
	if o == nil || IsNil(o.Pid) {
		return nil, false
	}
	return o.Pid, true
}

// HasPid returns a boolean if a field has been set.
func (o *Box) HasPid() bool {
	if o != nil && !IsNil(o.Pid) {
		return true
	}

	return false
}

// SetPid gets a reference to the given float32 and assigns it to the Pid field.
func (o *Box) SetPid(v float32) {
	o.Pid = &v
}

// GetImage returns the Image field value
func (o *Box) GetImage() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Image
}

// GetImageOk returns a tuple with the Image field value
// and a boolean to check if the value has been set.
func (o *Box) GetImageOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Image, true
}

// SetImage sets field value
func (o *Box) SetImage(v string) {
	o.Image = v
}

// GetCpus returns the Cpus field value
func (o *Box) GetCpus() float32 {
	if o == nil {
		var ret float32
		return ret
	}

	return o.Cpus
}

// GetCpusOk returns a tuple with the Cpus field value
// and a boolean to check if the value has been set.
func (o *Box) GetCpusOk() (*float32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Cpus, true
}

// SetCpus sets field value
func (o *Box) SetCpus(v float32) {
	o.Cpus = v
}

// GetMemoryMib returns the MemoryMib field value
func (o *Box) GetMemoryMib() float32 {
	if o == nil {
		var ret float32
		return ret
	}

	return o.MemoryMib
}

// GetMemoryMibOk returns a tuple with the MemoryMib field value
// and a boolean to check if the value has been set.
func (o *Box) GetMemoryMibOk() (*float32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.MemoryMib, true
}

// SetMemoryMib sets field value
func (o *Box) SetMemoryMib(v float32) {
	o.MemoryMib = v
}

// GetLabels returns the Labels field value
func (o *Box) GetLabels() map[string]string {
	if o == nil {
		var ret map[string]string
		return ret
	}

	return o.Labels
}

// GetLabelsOk returns a tuple with the Labels field value
// and a boolean to check if the value has been set.
func (o *Box) GetLabelsOk() (*map[string]string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Labels, true
}

// SetLabels sets field value
func (o *Box) SetLabels(v map[string]string) {
	o.Labels = v
}

func (o Box) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o Box) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["box_id"] = o.BoxId
	if !IsNil(o.Name) {
		toSerialize["name"] = o.Name
	}
	toSerialize["status"] = o.Status
	toSerialize["created_at"] = o.CreatedAt
	toSerialize["updated_at"] = o.UpdatedAt
	if !IsNil(o.Pid) {
		toSerialize["pid"] = o.Pid
	}
	toSerialize["image"] = o.Image
	toSerialize["cpus"] = o.Cpus
	toSerialize["memory_mib"] = o.MemoryMib
	toSerialize["labels"] = o.Labels

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *Box) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"box_id",
		"status",
		"created_at",
		"updated_at",
		"image",
		"cpus",
		"memory_mib",
		"labels",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varBox := _Box{}

	err = json.Unmarshal(data, &varBox)

	if err != nil {
		return err
	}

	*o = Box(varBox)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "box_id")
		delete(additionalProperties, "name")
		delete(additionalProperties, "status")
		delete(additionalProperties, "created_at")
		delete(additionalProperties, "updated_at")
		delete(additionalProperties, "pid")
		delete(additionalProperties, "image")
		delete(additionalProperties, "cpus")
		delete(additionalProperties, "memory_mib")
		delete(additionalProperties, "labels")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableBox struct {
	value *Box
	isSet bool
}

func (v NullableBox) Get() *Box {
	return v.value
}

func (v *NullableBox) Set(val *Box) {
	v.value = val
	v.isSet = true
}

func (v NullableBox) IsSet() bool {
	return v.isSet
}

func (v *NullableBox) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableBox(val *Box) *NullableBox {
	return &NullableBox{value: val, isSet: true}
}

func (v NullableBox) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableBox) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
