/*
BoxLite

BoxLite AI platform API Docs

API version: 1.0
Contact: support@boxlite.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package apiclient

import (
	"encoding/json"
	"fmt"
)

// checks if the ListBoxesResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ListBoxesResponse{}

// ListBoxesResponse struct for ListBoxesResponse
type ListBoxesResponse struct {
	Boxes []Box `json:"boxes"`
	// Token for the next page when pagination is available
	NextPageToken        *string `json:"next_page_token,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _ListBoxesResponse ListBoxesResponse

// NewListBoxesResponse instantiates a new ListBoxesResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewListBoxesResponse(boxes []Box) *ListBoxesResponse {
	this := ListBoxesResponse{}
	this.Boxes = boxes
	return &this
}

// NewListBoxesResponseWithDefaults instantiates a new ListBoxesResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewListBoxesResponseWithDefaults() *ListBoxesResponse {
	this := ListBoxesResponse{}
	return &this
}

// GetBoxes returns the Boxes field value
func (o *ListBoxesResponse) GetBoxes() []Box {
	if o == nil {
		var ret []Box
		return ret
	}

	return o.Boxes
}

// GetBoxesOk returns a tuple with the Boxes field value
// and a boolean to check if the value has been set.
func (o *ListBoxesResponse) GetBoxesOk() ([]Box, bool) {
	if o == nil {
		return nil, false
	}
	return o.Boxes, true
}

// SetBoxes sets field value
func (o *ListBoxesResponse) SetBoxes(v []Box) {
	o.Boxes = v
}

// GetNextPageToken returns the NextPageToken field value if set, zero value otherwise.
func (o *ListBoxesResponse) GetNextPageToken() string {
	if o == nil || IsNil(o.NextPageToken) {
		var ret string
		return ret
	}
	return *o.NextPageToken
}

// GetNextPageTokenOk returns a tuple with the NextPageToken field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ListBoxesResponse) GetNextPageTokenOk() (*string, bool) {
	if o == nil || IsNil(o.NextPageToken) {
		return nil, false
	}
	return o.NextPageToken, true
}

// HasNextPageToken returns a boolean if a field has been set.
func (o *ListBoxesResponse) HasNextPageToken() bool {
	if o != nil && !IsNil(o.NextPageToken) {
		return true
	}

	return false
}

// SetNextPageToken gets a reference to the given string and assigns it to the NextPageToken field.
func (o *ListBoxesResponse) SetNextPageToken(v string) {
	o.NextPageToken = &v
}

func (o ListBoxesResponse) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ListBoxesResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["boxes"] = o.Boxes
	if !IsNil(o.NextPageToken) {
		toSerialize["next_page_token"] = o.NextPageToken
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *ListBoxesResponse) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"boxes",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varListBoxesResponse := _ListBoxesResponse{}

	err = json.Unmarshal(data, &varListBoxesResponse)

	if err != nil {
		return err
	}

	*o = ListBoxesResponse(varListBoxesResponse)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "boxes")
		delete(additionalProperties, "next_page_token")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableListBoxesResponse struct {
	value *ListBoxesResponse
	isSet bool
}

func (v NullableListBoxesResponse) Get() *ListBoxesResponse {
	return v.value
}

func (v *NullableListBoxesResponse) Set(val *ListBoxesResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableListBoxesResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableListBoxesResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableListBoxesResponse(val *ListBoxesResponse) *NullableListBoxesResponse {
	return &NullableListBoxesResponse{value: val, isSet: true}
}

func (v NullableListBoxesResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableListBoxesResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
