/*
BoxLite

BoxLite AI platform API Docs

API version: 1.0
Contact: support@boxlite.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package apiclient

// SetSavedImageGeneralStatusDto struct for SetSavedImageGeneralStatusDto.
type SetSavedImageGeneralStatusDto = SetSnapshotGeneralStatusDto
