/*
BoxLite

BoxLite AI platform API Docs

API version: 1.0
Contact: support@boxlite.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package apiclient

import (
	"encoding/json"
	"fmt"
)

// checks if the RunnerArtifactCacheDto type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &RunnerArtifactCacheDto{}

// RunnerArtifactCacheDto struct for RunnerArtifactCacheDto
type RunnerArtifactCacheDto struct {
	// Runner artifact cache ID
	RunnerArtifactCacheId string `json:"runnerArtifactCacheId"`
	// Runner ID
	RunnerId string `json:"runnerId"`
	// Runner domain
	RunnerDomain         *string `json:"runnerDomain,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _RunnerArtifactCacheDto RunnerArtifactCacheDto

// NewRunnerArtifactCacheDto instantiates a new RunnerArtifactCacheDto object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewRunnerArtifactCacheDto(runnerArtifactCacheId string, runnerId string) *RunnerArtifactCacheDto {
	this := RunnerArtifactCacheDto{}
	this.RunnerArtifactCacheId = runnerArtifactCacheId
	this.RunnerId = runnerId
	return &this
}

// NewRunnerArtifactCacheDtoWithDefaults instantiates a new RunnerArtifactCacheDto object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewRunnerArtifactCacheDtoWithDefaults() *RunnerArtifactCacheDto {
	this := RunnerArtifactCacheDto{}
	return &this
}

// GetRunnerArtifactCacheId returns the RunnerArtifactCacheId field value
func (o *RunnerArtifactCacheDto) GetRunnerArtifactCacheId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.RunnerArtifactCacheId
}

// GetRunnerArtifactCacheIdOk returns a tuple with the RunnerArtifactCacheId field value
// and a boolean to check if the value has been set.
func (o *RunnerArtifactCacheDto) GetRunnerArtifactCacheIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.RunnerArtifactCacheId, true
}

// SetRunnerArtifactCacheId sets field value
func (o *RunnerArtifactCacheDto) SetRunnerArtifactCacheId(v string) {
	o.RunnerArtifactCacheId = v
}

// GetRunnerId returns the RunnerId field value
func (o *RunnerArtifactCacheDto) GetRunnerId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.RunnerId
}

// GetRunnerIdOk returns a tuple with the RunnerId field value
// and a boolean to check if the value has been set.
func (o *RunnerArtifactCacheDto) GetRunnerIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.RunnerId, true
}

// SetRunnerId sets field value
func (o *RunnerArtifactCacheDto) SetRunnerId(v string) {
	o.RunnerId = v
}

// GetRunnerDomain returns the RunnerDomain field value if set, zero value otherwise.
func (o *RunnerArtifactCacheDto) GetRunnerDomain() string {
	if o == nil || IsNil(o.RunnerDomain) {
		var ret string
		return ret
	}
	return *o.RunnerDomain
}

// GetRunnerDomainOk returns a tuple with the RunnerDomain field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RunnerArtifactCacheDto) GetRunnerDomainOk() (*string, bool) {
	if o == nil || IsNil(o.RunnerDomain) {
		return nil, false
	}
	return o.RunnerDomain, true
}

// HasRunnerDomain returns a boolean if a field has been set.
func (o *RunnerArtifactCacheDto) HasRunnerDomain() bool {
	if o != nil && !IsNil(o.RunnerDomain) {
		return true
	}

	return false
}

// SetRunnerDomain gets a reference to the given string and assigns it to the RunnerDomain field.
func (o *RunnerArtifactCacheDto) SetRunnerDomain(v string) {
	o.RunnerDomain = &v
}

func (o RunnerArtifactCacheDto) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o RunnerArtifactCacheDto) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["runnerArtifactCacheId"] = o.RunnerArtifactCacheId
	toSerialize["runnerId"] = o.RunnerId
	if !IsNil(o.RunnerDomain) {
		toSerialize["runnerDomain"] = o.RunnerDomain
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *RunnerArtifactCacheDto) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"runnerArtifactCacheId",
		"runnerId",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varRunnerArtifactCacheDto := _RunnerArtifactCacheDto{}

	err = json.Unmarshal(data, &varRunnerArtifactCacheDto)

	if err != nil {
		return err
	}

	*o = RunnerArtifactCacheDto(varRunnerArtifactCacheDto)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "runnerArtifactCacheId")
		delete(additionalProperties, "runnerId")
		delete(additionalProperties, "runnerDomain")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableRunnerArtifactCacheDto struct {
	value *RunnerArtifactCacheDto
	isSet bool
}

func (v NullableRunnerArtifactCacheDto) Get() *RunnerArtifactCacheDto {
	return v.value
}

func (v *NullableRunnerArtifactCacheDto) Set(val *RunnerArtifactCacheDto) {
	v.value = val
	v.isSet = true
}

func (v NullableRunnerArtifactCacheDto) IsSet() bool {
	return v.isSet
}

func (v *NullableRunnerArtifactCacheDto) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableRunnerArtifactCacheDto(val *RunnerArtifactCacheDto) *NullableRunnerArtifactCacheDto {
	return &NullableRunnerArtifactCacheDto{value: val, isSet: true}
}

func (v NullableRunnerArtifactCacheDto) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableRunnerArtifactCacheDto) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
