/*
BoxLite

BoxLite AI platform API Docs

API version: 1.0
Contact: support@boxlite.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package apiclient

import (
	"encoding/json"
	"fmt"
	"time"
)

// checks if the BoxTemplateDto type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &BoxTemplateDto{}

// BoxTemplateDto struct for BoxTemplateDto
type BoxTemplateDto struct {
	Id             string  `json:"id"`
	OrganizationId *string `json:"organizationId,omitempty"`
	General        bool    `json:"general"`
	Name           string  `json:"name"`
	DisplayName    string  `json:"displayName"`
	Description    *string `json:"description,omitempty"`
	// Agent/runtime capabilities included in this official image
	Capabilities     []string                       `json:"capabilities,omitempty"`
	ArtifactRef      *string                        `json:"artifactRef,omitempty"`
	State            BoxTemplateState               `json:"state"`
	ErrorReason      *string                        `json:"errorReason,omitempty"`
	DefaultResources BoxTemplateDefaultResourcesDto `json:"defaultResources"`
	CreatedAt        time.Time                      `json:"createdAt"`
	UpdatedAt        time.Time                      `json:"updatedAt"`
	LastUsedAt       *time.Time                     `json:"lastUsedAt,omitempty"`
	// Build information for this template
	BuildInfo *BuildInfo `json:"buildInfo,omitempty"`
	// The initial runner ID of the template
	InitialRunnerId *string `json:"initialRunnerId,omitempty"`
	// IDs of regions where the template is available to this organization
	RegionIds            []string `json:"regionIds,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _BoxTemplateDto BoxTemplateDto

// NewBoxTemplateDto instantiates a new BoxTemplateDto object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewBoxTemplateDto(id string, general bool, name string, displayName string, state BoxTemplateState, defaultResources BoxTemplateDefaultResourcesDto, createdAt time.Time, updatedAt time.Time) *BoxTemplateDto {
	this := BoxTemplateDto{}
	this.Id = id
	this.General = general
	this.Name = name
	this.DisplayName = displayName
	this.State = state
	this.DefaultResources = defaultResources
	this.CreatedAt = createdAt
	this.UpdatedAt = updatedAt
	return &this
}

// NewBoxTemplateDtoWithDefaults instantiates a new BoxTemplateDto object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewBoxTemplateDtoWithDefaults() *BoxTemplateDto {
	this := BoxTemplateDto{}
	return &this
}

// GetId returns the Id field value
func (o *BoxTemplateDto) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *BoxTemplateDto) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *BoxTemplateDto) SetId(v string) {
	o.Id = v
}

// GetOrganizationId returns the OrganizationId field value if set, zero value otherwise.
func (o *BoxTemplateDto) GetOrganizationId() string {
	if o == nil || IsNil(o.OrganizationId) {
		var ret string
		return ret
	}
	return *o.OrganizationId
}

// GetOrganizationIdOk returns a tuple with the OrganizationId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BoxTemplateDto) GetOrganizationIdOk() (*string, bool) {
	if o == nil || IsNil(o.OrganizationId) {
		return nil, false
	}
	return o.OrganizationId, true
}

// HasOrganizationId returns a boolean if a field has been set.
func (o *BoxTemplateDto) HasOrganizationId() bool {
	if o != nil && !IsNil(o.OrganizationId) {
		return true
	}

	return false
}

// SetOrganizationId gets a reference to the given string and assigns it to the OrganizationId field.
func (o *BoxTemplateDto) SetOrganizationId(v string) {
	o.OrganizationId = &v
}

// GetGeneral returns the General field value
func (o *BoxTemplateDto) GetGeneral() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.General
}

// GetGeneralOk returns a tuple with the General field value
// and a boolean to check if the value has been set.
func (o *BoxTemplateDto) GetGeneralOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.General, true
}

// SetGeneral sets field value
func (o *BoxTemplateDto) SetGeneral(v bool) {
	o.General = v
}

// GetName returns the Name field value
func (o *BoxTemplateDto) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *BoxTemplateDto) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *BoxTemplateDto) SetName(v string) {
	o.Name = v
}

// GetDisplayName returns the DisplayName field value
func (o *BoxTemplateDto) GetDisplayName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.DisplayName
}

// GetDisplayNameOk returns a tuple with the DisplayName field value
// and a boolean to check if the value has been set.
func (o *BoxTemplateDto) GetDisplayNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.DisplayName, true
}

// SetDisplayName sets field value
func (o *BoxTemplateDto) SetDisplayName(v string) {
	o.DisplayName = v
}

// GetDescription returns the Description field value if set, zero value otherwise.
func (o *BoxTemplateDto) GetDescription() string {
	if o == nil || IsNil(o.Description) {
		var ret string
		return ret
	}
	return *o.Description
}

// GetDescriptionOk returns a tuple with the Description field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BoxTemplateDto) GetDescriptionOk() (*string, bool) {
	if o == nil || IsNil(o.Description) {
		return nil, false
	}
	return o.Description, true
}

// HasDescription returns a boolean if a field has been set.
func (o *BoxTemplateDto) HasDescription() bool {
	if o != nil && !IsNil(o.Description) {
		return true
	}

	return false
}

// SetDescription gets a reference to the given string and assigns it to the Description field.
func (o *BoxTemplateDto) SetDescription(v string) {
	o.Description = &v
}

// GetCapabilities returns the Capabilities field value if set, zero value otherwise.
func (o *BoxTemplateDto) GetCapabilities() []string {
	if o == nil || IsNil(o.Capabilities) {
		var ret []string
		return ret
	}
	return o.Capabilities
}

// GetCapabilitiesOk returns a tuple with the Capabilities field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BoxTemplateDto) GetCapabilitiesOk() ([]string, bool) {
	if o == nil || IsNil(o.Capabilities) {
		return nil, false
	}
	return o.Capabilities, true
}

// HasCapabilities returns a boolean if a field has been set.
func (o *BoxTemplateDto) HasCapabilities() bool {
	if o != nil && !IsNil(o.Capabilities) {
		return true
	}

	return false
}

// SetCapabilities gets a reference to the given []string and assigns it to the Capabilities field.
func (o *BoxTemplateDto) SetCapabilities(v []string) {
	o.Capabilities = v
}

// GetArtifactRef returns the ArtifactRef field value if set, zero value otherwise.
func (o *BoxTemplateDto) GetArtifactRef() string {
	if o == nil || IsNil(o.ArtifactRef) {
		var ret string
		return ret
	}
	return *o.ArtifactRef
}

// GetArtifactRefOk returns a tuple with the ArtifactRef field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BoxTemplateDto) GetArtifactRefOk() (*string, bool) {
	if o == nil || IsNil(o.ArtifactRef) {
		return nil, false
	}
	return o.ArtifactRef, true
}

// HasArtifactRef returns a boolean if a field has been set.
func (o *BoxTemplateDto) HasArtifactRef() bool {
	if o != nil && !IsNil(o.ArtifactRef) {
		return true
	}

	return false
}

// SetArtifactRef gets a reference to the given string and assigns it to the ArtifactRef field.
func (o *BoxTemplateDto) SetArtifactRef(v string) {
	o.ArtifactRef = &v
}

// GetState returns the State field value
func (o *BoxTemplateDto) GetState() BoxTemplateState {
	if o == nil {
		var ret BoxTemplateState
		return ret
	}

	return o.State
}

// GetStateOk returns a tuple with the State field value
// and a boolean to check if the value has been set.
func (o *BoxTemplateDto) GetStateOk() (*BoxTemplateState, bool) {
	if o == nil {
		return nil, false
	}
	return &o.State, true
}

// SetState sets field value
func (o *BoxTemplateDto) SetState(v BoxTemplateState) {
	o.State = v
}

// GetErrorReason returns the ErrorReason field value if set, zero value otherwise.
func (o *BoxTemplateDto) GetErrorReason() string {
	if o == nil || IsNil(o.ErrorReason) {
		var ret string
		return ret
	}
	return *o.ErrorReason
}

// GetErrorReasonOk returns a tuple with the ErrorReason field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BoxTemplateDto) GetErrorReasonOk() (*string, bool) {
	if o == nil || IsNil(o.ErrorReason) {
		return nil, false
	}
	return o.ErrorReason, true
}

// HasErrorReason returns a boolean if a field has been set.
func (o *BoxTemplateDto) HasErrorReason() bool {
	if o != nil && !IsNil(o.ErrorReason) {
		return true
	}

	return false
}

// SetErrorReason gets a reference to the given string and assigns it to the ErrorReason field.
func (o *BoxTemplateDto) SetErrorReason(v string) {
	o.ErrorReason = &v
}

// GetDefaultResources returns the DefaultResources field value
func (o *BoxTemplateDto) GetDefaultResources() BoxTemplateDefaultResourcesDto {
	if o == nil {
		var ret BoxTemplateDefaultResourcesDto
		return ret
	}

	return o.DefaultResources
}

// GetDefaultResourcesOk returns a tuple with the DefaultResources field value
// and a boolean to check if the value has been set.
func (o *BoxTemplateDto) GetDefaultResourcesOk() (*BoxTemplateDefaultResourcesDto, bool) {
	if o == nil {
		return nil, false
	}
	return &o.DefaultResources, true
}

// SetDefaultResources sets field value
func (o *BoxTemplateDto) SetDefaultResources(v BoxTemplateDefaultResourcesDto) {
	o.DefaultResources = v
}

// GetCreatedAt returns the CreatedAt field value
func (o *BoxTemplateDto) GetCreatedAt() time.Time {
	if o == nil {
		var ret time.Time
		return ret
	}

	return o.CreatedAt
}

// GetCreatedAtOk returns a tuple with the CreatedAt field value
// and a boolean to check if the value has been set.
func (o *BoxTemplateDto) GetCreatedAtOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CreatedAt, true
}

// SetCreatedAt sets field value
func (o *BoxTemplateDto) SetCreatedAt(v time.Time) {
	o.CreatedAt = v
}

// GetUpdatedAt returns the UpdatedAt field value
func (o *BoxTemplateDto) GetUpdatedAt() time.Time {
	if o == nil {
		var ret time.Time
		return ret
	}

	return o.UpdatedAt
}

// GetUpdatedAtOk returns a tuple with the UpdatedAt field value
// and a boolean to check if the value has been set.
func (o *BoxTemplateDto) GetUpdatedAtOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return &o.UpdatedAt, true
}

// SetUpdatedAt sets field value
func (o *BoxTemplateDto) SetUpdatedAt(v time.Time) {
	o.UpdatedAt = v
}

// GetLastUsedAt returns the LastUsedAt field value if set, zero value otherwise.
func (o *BoxTemplateDto) GetLastUsedAt() time.Time {
	if o == nil || IsNil(o.LastUsedAt) {
		var ret time.Time
		return ret
	}
	return *o.LastUsedAt
}

// GetLastUsedAtOk returns a tuple with the LastUsedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BoxTemplateDto) GetLastUsedAtOk() (*time.Time, bool) {
	if o == nil || IsNil(o.LastUsedAt) {
		return nil, false
	}
	return o.LastUsedAt, true
}

// HasLastUsedAt returns a boolean if a field has been set.
func (o *BoxTemplateDto) HasLastUsedAt() bool {
	if o != nil && !IsNil(o.LastUsedAt) {
		return true
	}

	return false
}

// SetLastUsedAt gets a reference to the given time.Time and assigns it to the LastUsedAt field.
func (o *BoxTemplateDto) SetLastUsedAt(v time.Time) {
	o.LastUsedAt = &v
}

// GetBuildInfo returns the BuildInfo field value if set, zero value otherwise.
func (o *BoxTemplateDto) GetBuildInfo() BuildInfo {
	if o == nil || IsNil(o.BuildInfo) {
		var ret BuildInfo
		return ret
	}
	return *o.BuildInfo
}

// GetBuildInfoOk returns a tuple with the BuildInfo field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BoxTemplateDto) GetBuildInfoOk() (*BuildInfo, bool) {
	if o == nil || IsNil(o.BuildInfo) {
		return nil, false
	}
	return o.BuildInfo, true
}

// HasBuildInfo returns a boolean if a field has been set.
func (o *BoxTemplateDto) HasBuildInfo() bool {
	if o != nil && !IsNil(o.BuildInfo) {
		return true
	}

	return false
}

// SetBuildInfo gets a reference to the given BuildInfo and assigns it to the BuildInfo field.
func (o *BoxTemplateDto) SetBuildInfo(v BuildInfo) {
	o.BuildInfo = &v
}

// GetInitialRunnerId returns the InitialRunnerId field value if set, zero value otherwise.
func (o *BoxTemplateDto) GetInitialRunnerId() string {
	if o == nil || IsNil(o.InitialRunnerId) {
		var ret string
		return ret
	}
	return *o.InitialRunnerId
}

// GetInitialRunnerIdOk returns a tuple with the InitialRunnerId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BoxTemplateDto) GetInitialRunnerIdOk() (*string, bool) {
	if o == nil || IsNil(o.InitialRunnerId) {
		return nil, false
	}
	return o.InitialRunnerId, true
}

// HasInitialRunnerId returns a boolean if a field has been set.
func (o *BoxTemplateDto) HasInitialRunnerId() bool {
	if o != nil && !IsNil(o.InitialRunnerId) {
		return true
	}

	return false
}

// SetInitialRunnerId gets a reference to the given string and assigns it to the InitialRunnerId field.
func (o *BoxTemplateDto) SetInitialRunnerId(v string) {
	o.InitialRunnerId = &v
}

// GetRegionIds returns the RegionIds field value if set, zero value otherwise.
func (o *BoxTemplateDto) GetRegionIds() []string {
	if o == nil || IsNil(o.RegionIds) {
		var ret []string
		return ret
	}
	return o.RegionIds
}

// GetRegionIdsOk returns a tuple with the RegionIds field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BoxTemplateDto) GetRegionIdsOk() ([]string, bool) {
	if o == nil || IsNil(o.RegionIds) {
		return nil, false
	}
	return o.RegionIds, true
}

// HasRegionIds returns a boolean if a field has been set.
func (o *BoxTemplateDto) HasRegionIds() bool {
	if o != nil && !IsNil(o.RegionIds) {
		return true
	}

	return false
}

// SetRegionIds gets a reference to the given []string and assigns it to the RegionIds field.
func (o *BoxTemplateDto) SetRegionIds(v []string) {
	o.RegionIds = v
}

func (o BoxTemplateDto) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o BoxTemplateDto) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["id"] = o.Id
	if !IsNil(o.OrganizationId) {
		toSerialize["organizationId"] = o.OrganizationId
	}
	toSerialize["general"] = o.General
	toSerialize["name"] = o.Name
	toSerialize["displayName"] = o.DisplayName
	if !IsNil(o.Description) {
		toSerialize["description"] = o.Description
	}
	if !IsNil(o.Capabilities) {
		toSerialize["capabilities"] = o.Capabilities
	}
	if !IsNil(o.ArtifactRef) {
		toSerialize["artifactRef"] = o.ArtifactRef
	}
	toSerialize["state"] = o.State
	if !IsNil(o.ErrorReason) {
		toSerialize["errorReason"] = o.ErrorReason
	}
	toSerialize["defaultResources"] = o.DefaultResources
	toSerialize["createdAt"] = o.CreatedAt
	toSerialize["updatedAt"] = o.UpdatedAt
	if !IsNil(o.LastUsedAt) {
		toSerialize["lastUsedAt"] = o.LastUsedAt
	}
	if !IsNil(o.BuildInfo) {
		toSerialize["buildInfo"] = o.BuildInfo
	}
	if !IsNil(o.InitialRunnerId) {
		toSerialize["initialRunnerId"] = o.InitialRunnerId
	}
	if !IsNil(o.RegionIds) {
		toSerialize["regionIds"] = o.RegionIds
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *BoxTemplateDto) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"id",
		"general",
		"name",
		"displayName",
		"state",
		"defaultResources",
		"createdAt",
		"updatedAt",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varBoxTemplateDto := _BoxTemplateDto{}

	err = json.Unmarshal(data, &varBoxTemplateDto)

	if err != nil {
		return err
	}

	*o = BoxTemplateDto(varBoxTemplateDto)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "id")
		delete(additionalProperties, "organizationId")
		delete(additionalProperties, "general")
		delete(additionalProperties, "name")
		delete(additionalProperties, "displayName")
		delete(additionalProperties, "description")
		delete(additionalProperties, "capabilities")
		delete(additionalProperties, "artifactRef")
		delete(additionalProperties, "state")
		delete(additionalProperties, "errorReason")
		delete(additionalProperties, "defaultResources")
		delete(additionalProperties, "createdAt")
		delete(additionalProperties, "updatedAt")
		delete(additionalProperties, "lastUsedAt")
		delete(additionalProperties, "buildInfo")
		delete(additionalProperties, "initialRunnerId")
		delete(additionalProperties, "regionIds")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableBoxTemplateDto struct {
	value *BoxTemplateDto
	isSet bool
}

func (v NullableBoxTemplateDto) Get() *BoxTemplateDto {
	return v.value
}

func (v *NullableBoxTemplateDto) Set(val *BoxTemplateDto) {
	v.value = val
	v.isSet = true
}

func (v NullableBoxTemplateDto) IsSet() bool {
	return v.isSet
}

func (v *NullableBoxTemplateDto) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableBoxTemplateDto(val *BoxTemplateDto) *NullableBoxTemplateDto {
	return &NullableBoxTemplateDto{value: val, isSet: true}
}

func (v NullableBoxTemplateDto) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableBoxTemplateDto) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
