/*
BoxLite

BoxLite AI platform API Docs

API version: 1.0
Contact: support@boxlite.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package apiclient

import (
	"encoding/json"
	"fmt"
)

// checks if the PaginatedSavedImages type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &PaginatedSavedImages{}

// PaginatedSavedImages struct for PaginatedSavedImages
type PaginatedSavedImages struct {
	Items                []SavedImageDto `json:"items"`
	Total                float32         `json:"total"`
	Page                 float32         `json:"page"`
	TotalPages           float32         `json:"totalPages"`
	AdditionalProperties map[string]interface{}
}

type _PaginatedSavedImages PaginatedSavedImages

// NewPaginatedSavedImages instantiates a new PaginatedSavedImages object
func NewPaginatedSavedImages(items []SavedImageDto, total float32, page float32, totalPages float32) *PaginatedSavedImages {
	this := PaginatedSavedImages{}
	this.Items = items
	this.Total = total
	this.Page = page
	this.TotalPages = totalPages
	return &this
}

// NewPaginatedSavedImagesWithDefaults instantiates a new PaginatedSavedImages object
func NewPaginatedSavedImagesWithDefaults() *PaginatedSavedImages {
	this := PaginatedSavedImages{}
	return &this
}

func (o PaginatedSavedImages) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o PaginatedSavedImages) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["items"] = o.Items
	toSerialize["total"] = o.Total
	toSerialize["page"] = o.Page
	toSerialize["totalPages"] = o.TotalPages

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *PaginatedSavedImages) UnmarshalJSON(data []byte) (err error) {
	requiredProperties := []string{
		"items",
		"total",
		"page",
		"totalPages",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varPaginatedSavedImages := _PaginatedSavedImages{}

	err = json.Unmarshal(data, &varPaginatedSavedImages)

	if err != nil {
		return err
	}

	*o = PaginatedSavedImages(varPaginatedSavedImages)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "items")
		delete(additionalProperties, "total")
		delete(additionalProperties, "page")
		delete(additionalProperties, "totalPages")
		o.AdditionalProperties = additionalProperties
	}

	return err
}
