/*
BoxLite

BoxLite AI platform API Docs

API version: 1.0
Contact: support@boxlite.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package apiclient

import (
	"encoding/json"
	"fmt"
)

// checks if the SetBoxTemplateGeneralStatus type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SetBoxTemplateGeneralStatus{}

// SetBoxTemplateGeneralStatus struct for SetBoxTemplateGeneralStatus
type SetBoxTemplateGeneralStatus struct {
	// Whether the template is general
	General              bool `json:"general"`
	AdditionalProperties map[string]interface{}
}

type _SetBoxTemplateGeneralStatus SetBoxTemplateGeneralStatus

// NewSetBoxTemplateGeneralStatus instantiates a new SetBoxTemplateGeneralStatus object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSetBoxTemplateGeneralStatus(general bool) *SetBoxTemplateGeneralStatus {
	this := SetBoxTemplateGeneralStatus{}
	this.General = general
	return &this
}

// NewSetBoxTemplateGeneralStatusWithDefaults instantiates a new SetBoxTemplateGeneralStatus object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSetBoxTemplateGeneralStatusWithDefaults() *SetBoxTemplateGeneralStatus {
	this := SetBoxTemplateGeneralStatus{}
	return &this
}

// GetGeneral returns the General field value
func (o *SetBoxTemplateGeneralStatus) GetGeneral() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.General
}

// GetGeneralOk returns a tuple with the General field value
// and a boolean to check if the value has been set.
func (o *SetBoxTemplateGeneralStatus) GetGeneralOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.General, true
}

// SetGeneral sets field value
func (o *SetBoxTemplateGeneralStatus) SetGeneral(v bool) {
	o.General = v
}

func (o SetBoxTemplateGeneralStatus) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o SetBoxTemplateGeneralStatus) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["general"] = o.General

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *SetBoxTemplateGeneralStatus) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"general",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varSetBoxTemplateGeneralStatus := _SetBoxTemplateGeneralStatus{}

	err = json.Unmarshal(data, &varSetBoxTemplateGeneralStatus)

	if err != nil {
		return err
	}

	*o = SetBoxTemplateGeneralStatus(varSetBoxTemplateGeneralStatus)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "general")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableSetBoxTemplateGeneralStatus struct {
	value *SetBoxTemplateGeneralStatus
	isSet bool
}

func (v NullableSetBoxTemplateGeneralStatus) Get() *SetBoxTemplateGeneralStatus {
	return v.value
}

func (v *NullableSetBoxTemplateGeneralStatus) Set(val *SetBoxTemplateGeneralStatus) {
	v.value = val
	v.isSet = true
}

func (v NullableSetBoxTemplateGeneralStatus) IsSet() bool {
	return v.isSet
}

func (v *NullableSetBoxTemplateGeneralStatus) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSetBoxTemplateGeneralStatus(val *SetBoxTemplateGeneralStatus) *NullableSetBoxTemplateGeneralStatus {
	return &NullableSetBoxTemplateGeneralStatus{value: val, isSet: true}
}

func (v NullableSetBoxTemplateGeneralStatus) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSetBoxTemplateGeneralStatus) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
