/*
BoxLite

BoxLite AI platform API Docs

API version: 1.0
Contact: support@boxlite.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package apiclient

import (
	"encoding/json"
	"fmt"
)

// checks if the ArtifactRegistryCredentials type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ArtifactRegistryCredentials{}

// ArtifactRegistryCredentials struct for ArtifactRegistryCredentials
type ArtifactRegistryCredentials struct {
	// Artifact Registry username for the region
	Username string `json:"username"`
	// Artifact Registry password for the region
	Password             string `json:"password"`
	AdditionalProperties map[string]interface{}
}

type _ArtifactRegistryCredentials ArtifactRegistryCredentials

// NewArtifactRegistryCredentials instantiates a new ArtifactRegistryCredentials object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewArtifactRegistryCredentials(username string, password string) *ArtifactRegistryCredentials {
	this := ArtifactRegistryCredentials{}
	this.Username = username
	this.Password = password
	return &this
}

// NewArtifactRegistryCredentialsWithDefaults instantiates a new ArtifactRegistryCredentials object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewArtifactRegistryCredentialsWithDefaults() *ArtifactRegistryCredentials {
	this := ArtifactRegistryCredentials{}
	return &this
}

// GetUsername returns the Username field value
func (o *ArtifactRegistryCredentials) GetUsername() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Username
}

// GetUsernameOk returns a tuple with the Username field value
// and a boolean to check if the value has been set.
func (o *ArtifactRegistryCredentials) GetUsernameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Username, true
}

// SetUsername sets field value
func (o *ArtifactRegistryCredentials) SetUsername(v string) {
	o.Username = v
}

// GetPassword returns the Password field value
func (o *ArtifactRegistryCredentials) GetPassword() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Password
}

// GetPasswordOk returns a tuple with the Password field value
// and a boolean to check if the value has been set.
func (o *ArtifactRegistryCredentials) GetPasswordOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Password, true
}

// SetPassword sets field value
func (o *ArtifactRegistryCredentials) SetPassword(v string) {
	o.Password = v
}

func (o ArtifactRegistryCredentials) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ArtifactRegistryCredentials) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["username"] = o.Username
	toSerialize["password"] = o.Password

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *ArtifactRegistryCredentials) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"username",
		"password",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varArtifactRegistryCredentials := _ArtifactRegistryCredentials{}

	err = json.Unmarshal(data, &varArtifactRegistryCredentials)

	if err != nil {
		return err
	}

	*o = ArtifactRegistryCredentials(varArtifactRegistryCredentials)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "username")
		delete(additionalProperties, "password")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableArtifactRegistryCredentials struct {
	value *ArtifactRegistryCredentials
	isSet bool
}

func (v NullableArtifactRegistryCredentials) Get() *ArtifactRegistryCredentials {
	return v.value
}

func (v *NullableArtifactRegistryCredentials) Set(val *ArtifactRegistryCredentials) {
	v.value = val
	v.isSet = true
}

func (v NullableArtifactRegistryCredentials) IsSet() bool {
	return v.isSet
}

func (v *NullableArtifactRegistryCredentials) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableArtifactRegistryCredentials(val *ArtifactRegistryCredentials) *NullableArtifactRegistryCredentials {
	return &NullableArtifactRegistryCredentials{value: val, isSet: true}
}

func (v NullableArtifactRegistryCredentials) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableArtifactRegistryCredentials) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
