/*
BoxLite

BoxLite AI platform API Docs

API version: 1.0
Contact: support@boxlite.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package apiclient

import (
	"encoding/json"
	"fmt"
)

// BoxTemplateState the model 'BoxTemplateState'
type BoxTemplateState string

// List of BoxTemplateState
const (
	BOXTEMPLATESTATE_BUILDING     BoxTemplateState = "building"
	BOXTEMPLATESTATE_PENDING      BoxTemplateState = "pending"
	BOXTEMPLATESTATE_PULLING      BoxTemplateState = "pulling"
	BOXTEMPLATESTATE_ACTIVE       BoxTemplateState = "active"
	BOXTEMPLATESTATE_INACTIVE     BoxTemplateState = "inactive"
	BOXTEMPLATESTATE_ERROR        BoxTemplateState = "error"
	BOXTEMPLATESTATE_BUILD_FAILED BoxTemplateState = "build_failed"
	BOXTEMPLATESTATE_REMOVING     BoxTemplateState = "removing"
)

// All allowed values of BoxTemplateState enum
var AllowedBoxTemplateStateEnumValues = []BoxTemplateState{
	"building",
	"pending",
	"pulling",
	"active",
	"inactive",
	"error",
	"build_failed",
	"removing",
}

func (v *BoxTemplateState) UnmarshalJSON(src []byte) error {
	var value string
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}
	enumTypeValue := BoxTemplateState(value)
	for _, existing := range AllowedBoxTemplateStateEnumValues {
		if existing == enumTypeValue {
			*v = enumTypeValue
			return nil
		}
	}

	return fmt.Errorf("%+v is not a valid BoxTemplateState", value)
}

// NewBoxTemplateStateFromValue returns a pointer to a valid BoxTemplateState
// for the value passed as argument, or an error if the value passed is not allowed by the enum
func NewBoxTemplateStateFromValue(v string) (*BoxTemplateState, error) {
	ev := BoxTemplateState(v)
	if ev.IsValid() {
		return &ev, nil
	} else {
		return nil, fmt.Errorf("invalid value '%v' for BoxTemplateState: valid values are %v", v, AllowedBoxTemplateStateEnumValues)
	}
}

// IsValid return true if the value is valid for the enum, false otherwise
func (v BoxTemplateState) IsValid() bool {
	for _, existing := range AllowedBoxTemplateStateEnumValues {
		if existing == v {
			return true
		}
	}
	return false
}

// Ptr returns reference to BoxTemplateState value
func (v BoxTemplateState) Ptr() *BoxTemplateState {
	return &v
}

type NullableBoxTemplateState struct {
	value *BoxTemplateState
	isSet bool
}

func (v NullableBoxTemplateState) Get() *BoxTemplateState {
	return v.value
}

func (v *NullableBoxTemplateState) Set(val *BoxTemplateState) {
	v.value = val
	v.isSet = true
}

func (v NullableBoxTemplateState) IsSet() bool {
	return v.isSet
}

func (v *NullableBoxTemplateState) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableBoxTemplateState(val *BoxTemplateState) *NullableBoxTemplateState {
	return &NullableBoxTemplateState{value: val, isSet: true}
}

func (v NullableBoxTemplateState) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableBoxTemplateState) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
